In [12]:
!pip install rdkit -qq

In [13]:
!pip install optuna -qq

In [14]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.8)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (8.5.0)

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from catboost import CatBoostRegressor
from rdkit.Chem import PandasTools
from rdkit import DataStructs
import optuna

In [16]:
df = pd.read_csv('/content/drive/MyDrive/BigSolDB/BigSolDBv2.0.csv')
df = df.dropna()

In [17]:
df_processed = df.copy()

In [18]:
PandasTools.AddMoleculeColumnToFrame(
    df_processed,
    'SMILES_Solute',
    'Mol_Solute')
PandasTools.AddMoleculeColumnToFrame(
    df_processed,
    'SMILES_Solvent',
    'Mol_Solvent')
df_processed.head()

,SMILES_Solute,Temperature_K,Solvent,SMILES_Solvent,Solubility(mole_fraction),Solubility(mol/L),LogS(mol/L),Compound_Name,CAS,PubChem_CID,FDA_Approved,Source,Mol_Solute,Mol_Solvent
0,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,311.25,ethanol,CCO,0.0006,0.010083,-1.996419,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156d380>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9a10>
1,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,314.65,ethanol,CCO,0.0012,0.020100,-1.696799,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156ccf0>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9a80>
2,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,319.15,ethanol,CCO,0.0020,0.033356,-1.476824,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156cba0>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9af0>
3,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,322.15,ethanol,CCO,0.0050,0.083356,-1.079064,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156d770>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9b60>
4,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,324.15,ethanol,CCO,0.0139,0.233286,-0.632111,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156cc80>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9bd0>

In [19]:
from rdkit.Chem import AllChem

def morgan_fp(mol):
  morgan = AllChem.GetMorganGenerator(radius=2, fpSize=512)
  return morgan.GetFingerprint(mol)

In [20]:
df_processed['Morgan_Solute'] = df_processed['Mol_Solute'].apply(morgan_fp)
df_processed['Morgan_Solvent'] = df_processed['Mol_Solvent'].apply(morgan_fp)
df_processed.head()

,SMILES_Solute,Temperature_K,Solvent,SMILES_Solvent,Solubility(mole_fraction),Solubility(mol/L),LogS(mol/L),Compound_Name,CAS,PubChem_CID,FDA_Approved,Source,Mol_Solute,Mol_Solvent,Morgan_Solute,Morgan_Solvent
0,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,311.25,ethanol,CCO,0.0006,0.010083,-1.996419,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156d380>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9a10>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,314.65,ethanol,CCO,0.0012,0.020100,-1.696799,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156ccf0>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9a80>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,319.15,ethanol,CCO,0.0020,0.033356,-1.476824,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156cba0>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9af0>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,322.15,ethanol,CCO,0.0050,0.083356,-1.079064,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156d770>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9b60>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,324.15,ethanol,CCO,0.0139,0.233286,-0.632111,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x7862e156cc80>,<rdkit.Chem.rdchem.Mol object at 0x7862e03f9bd0>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [21]:
X = df_processed[['Temperature_K',
                  'Morgan_Solute',
                  'Morgan_Solvent']]
y = df_processed['LogS(mol/L)']

In [22]:
X['Morgan_Solute'] = X['Morgan_Solute'].tolist()
X['Morgan_Solvent'] = X['Morgan_Solvent'].tolist()

/tmp/ipython-input-1126101153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Morgan_Solute'] = X['Morgan_Solute'].tolist()
/tmp/ipython-input-1126101153.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Morgan_Solvent'] = X['Morgan_Solvent'].tolist()

In [23]:
def bitvect_to_array(bitvect):
  arr = np.zeros((1,), dtype=int)
  DataStructs.ConvertToNumpyArray(bitvect, arr)
  return arr

In [24]:
solute_fp = np.vstack(X['Morgan_Solute'].values)
solvent_fp = np.vstack(X['Morgan_Solvent'].values)

In [25]:
X_base = X.drop(['Morgan_Solute', 'Morgan_Solvent'], axis=1)

solute_df = pd.DataFrame(solute_fp, index=X.index).add_prefix('SoluteFP_')
solvent_df = pd.DataFrame(solvent_fp, index=X.index).add_prefix('SolventFP_')

X_final = pd.concat([X_base, solute_df, solvent_df], axis=1)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y,
    test_size=0.2,
    random_state=42
)

In [27]:
def objective(trial):
  iterations = trial.suggest_int('iterations', 10, 100)
  depth = trial.suggest_int('depth', 3, 10)
  learning_rate = trial.suggest_float('learning_rate', 0.01, 0.1)
  model = CatBoostRegressor(
        iterations=iterations,
        depth=depth,
        learning_rate=learning_rate,
        random_state=42
    )
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  rmse = mean_squared_error(y_test, y_pred)
  r2 = r2_score(y_test, y_pred)

  print(f"Trial {trial.number}: RMSE={rmse:.4f}, R2={r2:.4f}")

  return rmse

In [28]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print(f"Best trial value (RMSE): {study.best_value}")
print(f"Best hyperparameters: {study.best_params}")

[I 2025-10-10 19:59:31,175] A new study created in memory with name: no-name-c533dd14-3068-4542-971e-26c98421cc02

0:	learn: 1.2207620	total: 75.6ms	remaining: 6.88s
1:	learn: 1.2195081	total: 100ms	remaining: 4.5s
2:	learn: 1.2183417	total: 123ms	remaining: 3.66s
3:	learn: 1.2171572	total: 146ms	remaining: 3.21s
4:	learn: 1.2159807	total: 168ms	remaining: 2.93s
5:	learn: 1.2145897	total: 192ms	remaining: 2.75s
6:	learn: 1.2134772	total: 214ms	remaining: 2.6s
7:	learn: 1.2123972	total: 236ms	remaining: 2.48s
8:	learn: 1.2113265	total: 258ms	remaining: 2.38s
9:	learn: 1.2102529	total: 284ms	remaining: 2.33s
10:	learn: 1.2088289	total: 313ms	remaining: 2.31s
11:	learn: 1.2074444	total: 345ms	remaining: 2.3s
12:	learn: 1.2060983	total: 377ms	remaining: 2.29s
13:	learn: 1.2048884	total: 400ms	remaining: 2.23s
14:	learn: 1.2038870	total: 423ms	remaining: 2.17s
15:	learn: 1.2029014	total: 447ms	remaining: 2.12s
16:	learn: 1.2019284	total: 469ms	remaining: 2.07s
17:	learn: 1.2009454	total: 494ms	remaining: 2.03s
18:	learn: 1.1999860	total: 520ms	remaining: 2s
19:	learn: 1.1987786	total: 544ms	remaining: 1.96s
20:	learn: 1.1978615	total: 571ms	remaining: 1.93s
21:	learn: 1.1969309	total: 598ms	remaining: 1.9s
22:	learn: 1.1958221	total: 621ms	remaining: 1.86s
23:	learn: 1.1946176	total: 644ms	remaining: 1.82s
24:	learn: 1.1937714	total: 668ms	remaining: 1.79s
25:	learn: 1.1928659	total: 690ms	remaining: 1.75s
26:	learn: 1.1919577	total: 714ms	remaining: 1.72s
27:	learn: 1.1910936	total: 742ms	remaining: 1.7s
28:	learn: 1.1902084	total: 767ms	remaining: 1.67s
29:	learn: 1.1893509	total: 790ms	remaining: 1.63s
30:	learn: 1.1884999	total: 814ms	remaining: 1.6s
31:	learn: 1.1873990	total: 837ms	remaining: 1.57s
32:	learn: 1.1865583	total: 862ms	remaining: 1.54s
33:	learn: 1.1856115	total: 885ms	remaining: 1.51s
34:	learn: 1.1846814	total: 909ms	remaining: 1.48s
35:	learn: 1.1838681	total: 938ms	remaining: 1.46s
36:	learn: 1.1830654	total: 960ms	remaining: 1.43s
37:	learn: 1.1822419	total: 981ms	remaining: 1.39s
38:	learn: 1.1814374	total: 1s	remaining: 1.37s
39:	learn: 1.1805629	total: 1.03s	remaining: 1.34s
40:	learn: 1.1797915	total: 1.05s	remaining: 1.31s
41:	learn: 1.1787279	total: 1.07s	remaining: 1.28s
42:	learn: 1.1777288	total: 1.1s	remaining: 1.25s
43:	learn: 1.1769265	total: 1.13s	remaining: 1.23s
44:	learn: 1.1761770	total: 1.15s	remaining: 1.2s
45:	learn: 1.1754315	total: 1.18s	remaining: 1.18s
46:	learn: 1.1747040	total: 1.23s	remaining: 1.18s
47:	learn: 1.1737058	total: 1.26s	remaining: 1.15s
48:	learn: 1.1729259	total: 1.28s	remaining: 1.13s
49:	learn: 1.1722281	total: 1.31s	remaining: 1.1s
50:	learn: 1.1714881	total: 1.33s	remaining: 1.07s
51:	learn: 1.1706212	total: 1.36s	remaining: 1.05s
52:	learn: 1.1698058	total: 1.4s	remaining: 1.03s
53:	learn: 1.1690554	total: 1.43s	remaining: 1s
54:	learn: 1.1681223	total: 1.45s	remaining: 976ms
55:	learn: 1.1673964	total: 1.48s	remaining: 950ms
56:	learn: 1.1667460	total: 1.5s	remaining: 922ms
57:	learn: 1.1660691	total: 1.53s	remaining: 895ms
58:	learn: 1.1651953	total: 1.55s	remaining: 867ms
59:	learn: 1.1645393	total: 1.58s	remaining: 842ms
60:	learn: 1.1637563	total: 1.6s	remaining: 814ms
61:	learn: 1.1631247	total: 1.63s	remaining: 787ms
62:	learn: 1.1623962	total: 1.65s	remaining: 761ms
63:	learn: 1.1616973	total: 1.68s	remaining: 734ms
64:	learn: 1.1608661	total: 1.7s	remaining: 707ms
65:	learn: 1.1602137	total: 1.73s	remaining: 681ms
66:	learn: 1.1595134	total: 1.75s	remaining: 654ms
67:	learn: 1.1588815	total: 1.78s	remaining: 628ms
68:	learn: 1.1582263	total: 1.81s	remaining: 602ms
69:	learn: 1.1575781	total: 1.83s	remaining: 574ms
70:	learn: 1.1568851	total: 1.85s	remaining: 548ms
71:	learn: 1.1561480	total: 1.87s	remaining: 521ms
72:	learn: 1.1553383	total: 1.9s	remaining: 494ms
73:	learn: 1.1545515	total: 1.93s	remaining: 468ms
74:	learn: 1.1538755	total: 1.95s	remaining: 442ms
75:	learn: 1.1532086	total: 1.97s	remaining: 415ms
76:	learn: 1.1524079	total: 2s	remaining: 389ms
77:	learn: 1.1517133	total: 2.02s	remaining: 363ms
78:	learn: 1.1510207	total: 2.04s	remaining: 336ms
79:	learn: 1.1504355	total: 2.06s	remaining: 310ms
80:	learn: 1.1497603	total: 2.09s	remaining: 284ms
81:	learn: 1.1491217	total: 2.11s	remaining: 258ms
82:	learn: 1.1485166	total: 2.14s	remaining: 232ms
83:	learn: 1.1479278	total: 2.16s	remaining: 206ms
84:	learn: 1.1473560	total: 2.19s	remaining: 180ms
85:	learn: 1.1467796	total: 2.21s	remaining: 154ms

[I 2025-10-10 19:59:39,504] Trial 0 finished with value: 1.298932408472641 and parameters: {'iterations': 92, 'depth': 3, 'learning_rate': 0.014561778648245274}. Best is trial 0 with value: 1.298932408472641.

86:	learn: 1.1461043	total: 2.24s	remaining: 129ms
87:	learn: 1.1455347	total: 2.26s	remaining: 103ms
88:	learn: 1.1449897	total: 2.28s	remaining: 77ms
89:	learn: 1.1443863	total: 2.31s	remaining: 51.3ms
90:	learn: 1.1438382	total: 2.33s	remaining: 25.6ms
91:	learn: 1.1432791	total: 2.35s	remaining: 0us
Trial 0: RMSE=1.2989, R2=0.1191
0:	learn: 1.2158859	total: 207ms	remaining: 17s
1:	learn: 1.2103756	total: 378ms	remaining: 15.3s
2:	learn: 1.2048362	total: 542ms	remaining: 14.4s
3:	learn: 1.1989798	total: 705ms	remaining: 13.9s
4:	learn: 1.1930634	total: 885ms	remaining: 13.8s
5:	learn: 1.1876329	total: 1.04s	remaining: 13.4s
6:	learn: 1.1827906	total: 1.2s	remaining: 13s
7:	learn: 1.1774345	total: 1.38s	remaining: 12.9s
8:	learn: 1.1731623	total: 1.53s	remaining: 12.6s
9:	learn: 1.1679368	total: 1.73s	remaining: 12.7s
10:	learn: 1.1631876	total: 1.93s	remaining: 12.6s
11:	learn: 1.1584070	total: 2.1s	remaining: 12.4s
12:	learn: 1.1542666	total: 2.28s	remaining: 12.3s
13:	learn: 1.1491624	total: 2.5s	remaining: 12.3s
14:	learn: 1.1454002	total: 2.82s	remaining: 12.8s
15:	learn: 1.1414406	total: 3.13s	remaining: 13.1s
16:	learn: 1.1369926	total: 3.47s	remaining: 13.5s
17:	learn: 1.1312946	total: 3.81s	remaining: 13.8s
18:	learn: 1.1271593	total: 4.13s	remaining: 13.9s
19:	learn: 1.1223954	total: 4.46s	remaining: 14s
20:	learn: 1.1191254	total: 4.79s	remaining: 14.1s
21:	learn: 1.1157573	total: 5.11s	remaining: 14.2s
22:	learn: 1.1122703	total: 5.42s	remaining: 14.1s
23:	learn: 1.1082180	total: 5.73s	remaining: 14.1s
24:	learn: 1.1043905	total: 6.01s	remaining: 14s
25:	learn: 1.0999308	total: 6.33s	remaining: 13.9s
26:	learn: 1.0969031	total: 6.65s	remaining: 13.8s
27:	learn: 1.0933385	total: 6.89s	remaining: 13.5s
28:	learn: 1.0899170	total: 7.05s	remaining: 13.1s
29:	learn: 1.0870069	total: 7.22s	remaining: 12.8s
30:	learn: 1.0835437	total: 7.39s	remaining: 12.4s
31:	learn: 1.0797736	total: 7.58s	remaining: 12.1s
32:	learn: 1.0771487	total: 7.79s	remaining: 11.8s
33:	learn: 1.0745115	total: 7.98s	remaining: 11.5s
34:	learn: 1.0721825	total: 8.17s	remaining: 11.2s
35:	learn: 1.0690862	total: 8.36s	remaining: 10.9s
36:	learn: 1.0667174	total: 8.54s	remaining: 10.6s
37:	learn: 1.0634130	total: 8.7s	remaining: 10.3s
38:	learn: 1.0606592	total: 8.89s	remaining: 10s
39:	learn: 1.0575000	total: 9.05s	remaining: 9.73s
40:	learn: 1.0545689	total: 9.22s	remaining: 9.45s
41:	learn: 1.0521713	total: 9.41s	remaining: 9.18s
42:	learn: 1.0491731	total: 9.6s	remaining: 8.93s
43:	learn: 1.0466711	total: 9.77s	remaining: 8.66s
44:	learn: 1.0439174	total: 9.97s	remaining: 8.42s
45:	learn: 1.0415437	total: 10.2s	remaining: 8.17s
46:	learn: 1.0393889	total: 10.4s	remaining: 7.93s
47:	learn: 1.0373471	total: 10.5s	remaining: 7.68s
48:	learn: 1.0346939	total: 10.7s	remaining: 7.42s
49:	learn: 1.0315684	total: 10.9s	remaining: 7.17s
50:	learn: 1.0285649	total: 11.1s	remaining: 6.94s
51:	learn: 1.0265560	total: 11.2s	remaining: 6.7s
52:	learn: 1.0238212	total: 11.4s	remaining: 6.47s
53:	learn: 1.0208526	total: 11.6s	remaining: 6.25s
54:	learn: 1.0188903	total: 11.8s	remaining: 6.02s
55:	learn: 1.0162263	total: 12s	remaining: 5.79s
56:	learn: 1.0135717	total: 12.2s	remaining: 5.55s
57:	learn: 1.0111280	total: 12.3s	remaining: 5.32s
58:	learn: 1.0089979	total: 12.5s	remaining: 5.08s
59:	learn: 1.0063282	total: 12.7s	remaining: 4.86s
60:	learn: 1.0039495	total: 12.8s	remaining: 4.63s
61:	learn: 1.0021197	total: 13s	remaining: 4.41s
62:	learn: 1.0000622	total: 13.2s	remaining: 4.19s
63:	learn: 0.9976220	total: 13.4s	remaining: 3.98s
64:	learn: 0.9957205	total: 13.6s	remaining: 3.76s
65:	learn: 0.9936203	total: 13.8s	remaining: 3.55s
66:	learn: 0.9916304	total: 14s	remaining: 3.33s
67:	learn: 0.9895340	total: 14.2s	remaining: 3.13s
68:	learn: 0.9871306	total: 14.3s	remaining: 2.91s
69:	learn: 0.9851386	total: 14.5s	remaining: 2.7s
70:	learn: 0.9834366	total: 14.7s	remaining: 2.49s
71:	learn: 0.9816205	total: 14.9s	remaining: 2.28s
72:	learn: 0.9794922	total: 15.1s	remaining: 2.07s
73:	learn: 0.9779208	total: 15.2s	remaining: 1.85s
74:	learn: 0.9762849	total: 15.4s	remaining: 1.64s
75:	learn: 0.9746074	total: 15.6s	remaining: 1.44s
76:	learn: 0.9731904	total: 15.8s	remaining: 1.23s
77:	learn: 0.9713286	total: 16s	remaining: 1.02s
78:	learn: 0.9698153	total: 16.1s	remaining: 817ms
79:	learn: 0.9681211	total: 16.3s	remaining: 612ms
80:	learn: 0.9668145	total: 16.5s	remaining: 408ms
81:	learn: 0.9654659	total: 16.7s	remaining: 204ms

[I 2025-10-10 20:00:00,629] Trial 1 finished with value: 0.9357490486144466 and parameters: {'iterations': 83, 'depth': 9, 'learning_rate': 0.024222561273035157}. Best is trial 1 with value: 0.9357490486144466.

82:	learn: 0.9638478	total: 16.9s	remaining: 0us
Trial 1: RMSE=0.9357, R2=0.3654
0:	learn: 1.2134170	total: 38.9ms	remaining: 1.75s
1:	learn: 1.2047086	total: 74.8ms	remaining: 1.65s
2:	learn: 1.1968235	total: 108ms	remaining: 1.55s
3:	learn: 1.1897806	total: 145ms	remaining: 1.52s
4:	learn: 1.1815065	total: 185ms	remaining: 1.51s
5:	learn: 1.1755587	total: 223ms	remaining: 1.49s
6:	learn: 1.1682410	total: 261ms	remaining: 1.45s
7:	learn: 1.1615921	total: 298ms	remaining: 1.42s
8:	learn: 1.1548244	total: 338ms	remaining: 1.39s
9:	learn: 1.1497901	total: 372ms	remaining: 1.34s
10:	learn: 1.1446641	total: 410ms	remaining: 1.31s
11:	learn: 1.1401077	total: 444ms	remaining: 1.26s
12:	learn: 1.1353147	total: 485ms	remaining: 1.23s
13:	learn: 1.1302269	total: 520ms	remaining: 1.19s
14:	learn: 1.1246961	total: 559ms	remaining: 1.15s
15:	learn: 1.1198561	total: 615ms	remaining: 1.15s
16:	learn: 1.1154161	total: 659ms	remaining: 1.12s
17:	learn: 1.1106969	total: 698ms	remaining: 1.08s
18:	learn: 1.1064860	total: 732ms	remaining: 1.04s
19:	learn: 1.1029865	total: 766ms	remaining: 996ms
20:	learn: 1.0983427	total: 801ms	remaining: 954ms
21:	learn: 1.0948584	total: 838ms	remaining: 914ms
22:	learn: 1.0908647	total: 874ms	remaining: 874ms
23:	learn: 1.0877346	total: 908ms	remaining: 832ms
24:	learn: 1.0837428	total: 956ms	remaining: 803ms
25:	learn: 1.0803378	total: 991ms	remaining: 762ms
26:	learn: 1.0770661	total: 1.02s	remaining: 720ms
27:	learn: 1.0737116	total: 1.06s	remaining: 679ms
28:	learn: 1.0710651	total: 1.09s	remaining: 638ms
29:	learn: 1.0686656	total: 1.12s	remaining: 599ms
30:	learn: 1.0657179	total: 1.16s	remaining: 560ms
31:	learn: 1.0629900	total: 1.23s	remaining: 538ms
32:	learn: 1.0599015	total: 1.38s	remaining: 543ms
33:	learn: 1.0570470	total: 1.48s	remaining: 523ms
34:	learn: 1.0542128	total: 1.68s	remaining: 527ms
35:	learn: 1.0517959	total: 1.74s	remaining: 484ms
36:	learn: 1.0499795	total: 1.78s	remaining: 432ms
37:	learn: 1.0468139	total: 1.81s	remaining: 382ms
38:	learn: 1.0442718	total: 1.84s	remaining: 331ms
39:	learn: 1.0414103	total: 1.88s	remaining: 282ms
40:	learn: 1.0388900	total: 1.92s	remaining: 234ms
41:	learn: 1.0364469	total: 1.96s	remaining: 187ms
42:	learn: 1.0334225	total: 2s	remaining: 139ms
43:	learn: 1.0312614	total: 2.03s	remaining: 92.4ms
44:	learn: 1.0291310	total: 2.06s	remaining: 45.9ms

[I 2025-10-10 20:00:08,952] Trial 2 finished with value: 1.0561412554713643 and parameters: {'iterations': 46, 'depth': 5, 'learning_rate': 0.06418327477502031}. Best is trial 1 with value: 0.9357490486144466.

45:	learn: 1.0270470	total: 2.1s	remaining: 0us
Trial 2: RMSE=1.0561, R2=0.2837
0:	learn: 1.2173635	total: 117ms	remaining: 2.1s
1:	learn: 1.2120973	total: 219ms	remaining: 1.86s
2:	learn: 1.2071232	total: 324ms	remaining: 1.73s
3:	learn: 1.2030341	total: 415ms	remaining: 1.55s
4:	learn: 1.1988431	total: 512ms	remaining: 1.43s
5:	learn: 1.1945544	total: 612ms	remaining: 1.32s
6:	learn: 1.1901883	total: 735ms	remaining: 1.26s
7:	learn: 1.1859038	total: 847ms	remaining: 1.16s
8:	learn: 1.1817027	total: 961ms	remaining: 1.07s
9:	learn: 1.1769729	total: 1.07s	remaining: 962ms
10:	learn: 1.1732498	total: 1.19s	remaining: 865ms
11:	learn: 1.1696944	total: 1.29s	remaining: 753ms
12:	learn: 1.1661988	total: 1.39s	remaining: 641ms
13:	learn: 1.1623292	total: 1.48s	remaining: 528ms
14:	learn: 1.1586022	total: 1.58s	remaining: 422ms
15:	learn: 1.1552238	total: 1.7s	remaining: 318ms
16:	learn: 1.1518623	total: 1.83s	remaining: 215ms
17:	learn: 1.1477582	total: 1.92s	remaining: 107ms

[I 2025-10-10 20:00:15,117] Trial 3 finished with value: 1.3000485924604959 and parameters: {'iterations': 19, 'depth': 8, 'learning_rate': 0.022278209788610556}. Best is trial 1 with value: 0.9357490486144466.

18:	learn: 1.1444300	total: 2.03s	remaining: 0us
Trial 3: RMSE=1.3000, R2=0.1183
0:	learn: 1.2069605	total: 383ms	remaining: 27.9s
1:	learn: 1.1924920	total: 738ms	remaining: 26.6s
2:	learn: 1.1791494	total: 1.09s	remaining: 25.9s
3:	learn: 1.1655809	total: 1.47s	remaining: 25.8s
4:	learn: 1.1544247	total: 1.83s	remaining: 25.3s
5:	learn: 1.1430241	total: 2.19s	remaining: 24.8s
6:	learn: 1.1325140	total: 2.56s	remaining: 24.5s
7:	learn: 1.1222670	total: 2.91s	remaining: 24s
8:	learn: 1.1114317	total: 3.27s	remaining: 23.6s
9:	learn: 1.1022395	total: 3.64s	remaining: 23.3s
10:	learn: 1.0925272	total: 4s	remaining: 22.9s
11:	learn: 1.0843299	total: 4.34s	remaining: 22.4s
12:	learn: 1.0757555	total: 4.71s	remaining: 22.1s
13:	learn: 1.0676692	total: 5.07s	remaining: 21.7s
14:	learn: 1.0600045	total: 5.43s	remaining: 21.4s
15:	learn: 1.0515733	total: 5.8s	remaining: 21s
16:	learn: 1.0437065	total: 6.14s	remaining: 20.6s
17:	learn: 1.0380459	total: 6.5s	remaining: 20.2s
18:	learn: 1.0307336	total: 6.87s	remaining: 19.9s
19:	learn: 1.0243804	total: 7.22s	remaining: 19.5s
20:	learn: 1.0170269	total: 7.57s	remaining: 19.1s
21:	learn: 1.0105943	total: 7.94s	remaining: 18.8s
22:	learn: 1.0047777	total: 8.3s	remaining: 18.4s
23:	learn: 0.9998922	total: 8.66s	remaining: 18.1s
24:	learn: 0.9941179	total: 9.04s	remaining: 17.7s
25:	learn: 0.9885926	total: 9.39s	remaining: 17.3s
26:	learn: 0.9833598	total: 9.75s	remaining: 17s
27:	learn: 0.9791332	total: 10.3s	remaining: 16.9s
28:	learn: 0.9750567	total: 10.9s	remaining: 16.9s
29:	learn: 0.9700244	total: 11.5s	remaining: 16.9s
30:	learn: 0.9662337	total: 12s	remaining: 16.7s
31:	learn: 0.9605829	total: 12.7s	remaining: 16.6s
32:	learn: 0.9568579	total: 13.3s	remaining: 16.5s
33:	learn: 0.9516322	total: 13.8s	remaining: 16.3s
34:	learn: 0.9475637	total: 14.4s	remaining: 16.1s
35:	learn: 0.9422426	total: 14.8s	remaining: 15.6s
36:	learn: 0.9380621	total: 15.2s	remaining: 15.2s
37:	learn: 0.9352473	total: 15.5s	remaining: 14.7s
38:	learn: 0.9320089	total: 15.9s	remaining: 14.3s
39:	learn: 0.9262690	total: 16.3s	remaining: 13.8s
40:	learn: 0.9224432	total: 16.6s	remaining: 13.4s
41:	learn: 0.9180074	total: 17s	remaining: 12.9s
42:	learn: 0.9128394	total: 17.4s	remaining: 12.5s
43:	learn: 0.9093592	total: 17.8s	remaining: 12.1s
44:	learn: 0.9058026	total: 18.1s	remaining: 11.7s
45:	learn: 0.9024688	total: 18.5s	remaining: 11.3s
46:	learn: 0.8991784	total: 18.8s	remaining: 10.8s
47:	learn: 0.8956944	total: 19.2s	remaining: 10.4s
48:	learn: 0.8903958	total: 19.6s	remaining: 9.98s
49:	learn: 0.8874869	total: 19.9s	remaining: 9.56s
50:	learn: 0.8840669	total: 20.3s	remaining: 9.14s
51:	learn: 0.8817221	total: 20.6s	remaining: 8.73s
52:	learn: 0.8786738	total: 21s	remaining: 8.32s
53:	learn: 0.8750604	total: 21.4s	remaining: 7.91s
54:	learn: 0.8720911	total: 21.7s	remaining: 7.51s
55:	learn: 0.8687463	total: 22.1s	remaining: 7.1s
56:	learn: 0.8645865	total: 22.4s	remaining: 6.69s
57:	learn: 0.8618865	total: 23.1s	remaining: 6.36s
58:	learn: 0.8588518	total: 23.6s	remaining: 6s
59:	learn: 0.8564998	total: 24s	remaining: 5.59s
60:	learn: 0.8536755	total: 24.3s	remaining: 5.18s
61:	learn: 0.8505674	total: 24.8s	remaining: 4.79s
62:	learn: 0.8477957	total: 25.3s	remaining: 4.42s
63:	learn: 0.8450689	total: 26s	remaining: 4.06s
64:	learn: 0.8431447	total: 26.5s	remaining: 3.67s
65:	learn: 0.8408725	total: 27.1s	remaining: 3.28s
66:	learn: 0.8378992	total: 27.7s	remaining: 2.89s
67:	learn: 0.8349410	total: 28.3s	remaining: 2.5s
68:	learn: 0.8322134	total: 28.9s	remaining: 2.1s
69:	learn: 0.8300048	total: 29.4s	remaining: 1.68s
70:	learn: 0.8266879	total: 29.8s	remaining: 1.26s
71:	learn: 0.8241243	total: 30.1s	remaining: 837ms
72:	learn: 0.8218814	total: 30.5s	remaining: 418ms

[I 2025-10-10 20:00:51,982] Trial 4 finished with value: 0.6864084186774555 and parameters: {'iterations': 74, 'depth': 10, 'learning_rate': 0.05398268674267841}. Best is trial 4 with value: 0.6864084186774555.

73:	learn: 0.8191253	total: 30.8s	remaining: 0us
Trial 4: RMSE=0.6864, R2=0.5345
0:	learn: 1.2176839	total: 177ms	remaining: 15.1s
1:	learn: 1.2137446	total: 345ms	remaining: 14.5s
2:	learn: 1.2095887	total: 508ms	remaining: 14.1s
3:	learn: 1.2052167	total: 705ms	remaining: 14.4s
4:	learn: 1.2009567	total: 888ms	remaining: 14.4s
5:	learn: 1.1969404	total: 1.05s	remaining: 14s
6:	learn: 1.1933262	total: 1.21s	remaining: 13.7s
7:	learn: 1.1893852	total: 1.37s	remaining: 13.4s
8:	learn: 1.1857573	total: 1.53s	remaining: 13.1s
9:	learn: 1.1822981	total: 1.71s	remaining: 13s
10:	learn: 1.1784948	total: 1.88s	remaining: 12.8s
11:	learn: 1.1749294	total: 2.03s	remaining: 12.5s
12:	learn: 1.1712199	total: 2.21s	remaining: 12.4s
13:	learn: 1.1679649	total: 2.37s	remaining: 12.2s
14:	learn: 1.1649280	total: 2.53s	remaining: 12s
15:	learn: 1.1617428	total: 2.69s	remaining: 11.8s
16:	learn: 1.1583531	total: 2.88s	remaining: 11.7s
17:	learn: 1.1554428	total: 3.04s	remaining: 11.5s
18:	learn: 1.1522201	total: 3.21s	remaining: 11.3s
19:	learn: 1.1485135	total: 3.37s	remaining: 11.1s
20:	learn: 1.1459234	total: 3.53s	remaining: 10.9s
21:	learn: 1.1431694	total: 3.7s	remaining: 10.8s
22:	learn: 1.1403589	total: 3.88s	remaining: 10.6s
23:	learn: 1.1374344	total: 4.04s	remaining: 10.4s
24:	learn: 1.1346341	total: 4.22s	remaining: 10.3s
25:	learn: 1.1316531	total: 4.48s	remaining: 10.3s
26:	learn: 1.1287922	total: 4.74s	remaining: 10.4s
27:	learn: 1.1254879	total: 5.05s	remaining: 10.5s
28:	learn: 1.1227771	total: 5.33s	remaining: 10.5s
29:	learn: 1.1197273	total: 5.65s	remaining: 10.5s
30:	learn: 1.1169879	total: 5.93s	remaining: 10.5s
31:	learn: 1.1136561	total: 6.21s	remaining: 10.5s
32:	learn: 1.1110431	total: 6.5s	remaining: 10.4s
33:	learn: 1.1088426	total: 6.81s	remaining: 10.4s
34:	learn: 1.1062310	total: 7.1s	remaining: 10.4s
35:	learn: 1.1034042	total: 7.38s	remaining: 10.3s
36:	learn: 1.1008758	total: 7.71s	remaining: 10.2s
37:	learn: 1.0983299	total: 8.04s	remaining: 10.2s
38:	learn: 1.0961605	total: 8.36s	remaining: 10.1s
39:	learn: 1.0936536	total: 8.66s	remaining: 9.96s
40:	learn: 1.0910672	total: 8.87s	remaining: 9.73s
41:	learn: 1.0886881	total: 9.06s	remaining: 9.49s
42:	learn: 1.0860206	total: 9.25s	remaining: 9.25s
43:	learn: 1.0836491	total: 9.42s	remaining: 8.99s
44:	learn: 1.0811388	total: 9.59s	remaining: 8.73s
45:	learn: 1.0789836	total: 9.75s	remaining: 8.48s
46:	learn: 1.0768563	total: 9.92s	remaining: 8.23s
47:	learn: 1.0750220	total: 10.1s	remaining: 7.98s
48:	learn: 1.0729163	total: 10.3s	remaining: 7.75s
49:	learn: 1.0703966	total: 10.4s	remaining: 7.52s
50:	learn: 1.0684944	total: 10.6s	remaining: 7.29s
51:	learn: 1.0663095	total: 10.8s	remaining: 7.07s
52:	learn: 1.0641779	total: 11s	remaining: 6.84s
53:	learn: 1.0617715	total: 11.2s	remaining: 6.61s
54:	learn: 1.0597923	total: 11.3s	remaining: 6.39s
55:	learn: 1.0577021	total: 11.5s	remaining: 6.17s
56:	learn: 1.0559982	total: 11.7s	remaining: 5.94s
57:	learn: 1.0544506	total: 11.8s	remaining: 5.71s
58:	learn: 1.0527748	total: 12s	remaining: 5.5s
59:	learn: 1.0503708	total: 12.2s	remaining: 5.29s
60:	learn: 1.0486448	total: 12.4s	remaining: 5.09s
61:	learn: 1.0468192	total: 12.6s	remaining: 4.89s
62:	learn: 1.0448205	total: 12.8s	remaining: 4.67s
63:	learn: 1.0431223	total: 13s	remaining: 4.45s
64:	learn: 1.0415128	total: 13.1s	remaining: 4.25s
65:	learn: 1.0398016	total: 13.3s	remaining: 4.04s
66:	learn: 1.0380144	total: 13.5s	remaining: 3.84s
67:	learn: 1.0361503	total: 13.7s	remaining: 3.63s
68:	learn: 1.0341825	total: 13.9s	remaining: 3.42s
69:	learn: 1.0324302	total: 14s	remaining: 3.21s
70:	learn: 1.0308607	total: 14.2s	remaining: 3s
71:	learn: 1.0290763	total: 14.4s	remaining: 2.79s
72:	learn: 1.0270179	total: 14.6s	remaining: 2.6s
73:	learn: 1.0256085	total: 14.8s	remaining: 2.4s
74:	learn: 1.0237808	total: 15s	remaining: 2.19s
75:	learn: 1.0223675	total: 15.1s	remaining: 1.99s
76:	learn: 1.0207430	total: 15.3s	remaining: 1.79s
77:	learn: 1.0188910	total: 15.5s	remaining: 1.58s
78:	learn: 1.0172911	total: 15.7s	remaining: 1.39s
79:	learn: 1.0157888	total: 15.9s	remaining: 1.19s
80:	learn: 1.0142867	total: 16s	remaining: 990ms
81:	learn: 1.0129694	total: 16.2s	remaining: 792ms
82:	learn: 1.0116497	total: 16.4s	remaining: 594ms
83:	learn: 1.0103750	total: 16.6s	remaining: 395ms
84:	learn: 1.0085469	total: 16.8s	remaining: 198ms
85:	learn: 1.0070054	total: 17s	remaining: 0us

[I 2025-10-10 20:01:13,127] Trial 5 finished with value: 1.018431183233279 and parameters: {'iterations': 86, 'depth': 9, 'learning_rate': 0.017111372211740184}. Best is trial 4 with value: 0.6864084186774555.

Trial 5: RMSE=1.0184, R2=0.3093
0:	learn: 1.2113884	total: 88.4ms	remaining: 4.07s
1:	learn: 1.2004575	total: 179ms	remaining: 4.02s
2:	learn: 1.1909767	total: 259ms	remaining: 3.8s
3:	learn: 1.1809374	total: 359ms	remaining: 3.85s
4:	learn: 1.1732787	total: 443ms	remaining: 3.72s
5:	learn: 1.1646002	total: 533ms	remaining: 3.64s
6:	learn: 1.1573896	total: 638ms	remaining: 3.64s
7:	learn: 1.1509015	total: 727ms	remaining: 3.54s
8:	learn: 1.1447914	total: 801ms	remaining: 3.38s
9:	learn: 1.1385560	total: 877ms	remaining: 3.25s
10:	learn: 1.1331913	total: 962ms	remaining: 3.15s
11:	learn: 1.1281534	total: 1.03s	remaining: 3.01s
12:	learn: 1.1209858	total: 1.12s	remaining: 2.93s
13:	learn: 1.1163951	total: 1.19s	remaining: 2.8s
14:	learn: 1.1114677	total: 1.27s	remaining: 2.71s
15:	learn: 1.1055894	total: 1.32s	remaining: 2.55s
16:	learn: 1.0992379	total: 1.36s	remaining: 2.4s
17:	learn: 1.0938534	total: 1.4s	remaining: 2.26s
18:	learn: 1.0890895	total: 1.44s	remaining: 2.12s
19:	learn: 1.0852348	total: 1.47s	remaining: 1.99s
20:	learn: 1.0809478	total: 1.5s	remaining: 1.86s
21:	learn: 1.0774182	total: 1.54s	remaining: 1.75s
22:	learn: 1.0735604	total: 1.58s	remaining: 1.65s
23:	learn: 1.0682480	total: 1.61s	remaining: 1.55s
24:	learn: 1.0651242	total: 1.65s	remaining: 1.45s
25:	learn: 1.0611469	total: 1.68s	remaining: 1.36s
26:	learn: 1.0576174	total: 1.73s	remaining: 1.28s
27:	learn: 1.0540324	total: 1.78s	remaining: 1.21s
28:	learn: 1.0514570	total: 1.81s	remaining: 1.12s
29:	learn: 1.0488936	total: 1.85s	remaining: 1.05s
30:	learn: 1.0455880	total: 1.88s	remaining: 971ms
31:	learn: 1.0425132	total: 1.92s	remaining: 899ms
32:	learn: 1.0395957	total: 1.96s	remaining: 830ms
33:	learn: 1.0367861	total: 1.99s	remaining: 760ms
34:	learn: 1.0339263	total: 2.02s	remaining: 694ms
35:	learn: 1.0309227	total: 2.06s	remaining: 628ms
36:	learn: 1.0277694	total: 2.09s	remaining: 565ms
37:	learn: 1.0252344	total: 2.13s	remaining: 504ms
38:	learn: 1.0223843	total: 2.16s	remaining: 443ms
39:	learn: 1.0198259	total: 2.2s	remaining: 384ms
40:	learn: 1.0169326	total: 2.24s	remaining: 327ms
41:	learn: 1.0149752	total: 2.27s	remaining: 271ms
42:	learn: 1.0114784	total: 2.31s	remaining: 215ms
43:	learn: 1.0089970	total: 2.35s	remaining: 160ms
44:	learn: 1.0066889	total: 2.38s	remaining: 106ms
45:	learn: 1.0042909	total: 2.42s	remaining: 52.5ms

[I 2025-10-10 20:01:23,553] Trial 6 finished with value: 1.006610623378342 and parameters: {'iterations': 47, 'depth': 5, 'learning_rate': 0.07983906252390799}. Best is trial 4 with value: 0.6864084186774555.

46:	learn: 1.0020738	total: 2.45s	remaining: 0us
Trial 6: RMSE=1.0066, R2=0.3173
0:	learn: 1.2097919	total: 108ms	remaining: 5.73s
1:	learn: 1.1968036	total: 207ms	remaining: 5.39s
2:	learn: 1.1852255	total: 314ms	remaining: 5.34s
3:	learn: 1.1756772	total: 416ms	remaining: 5.2s
4:	learn: 1.1656494	total: 551ms	remaining: 5.39s
5:	learn: 1.1543467	total: 665ms	remaining: 5.32s
6:	learn: 1.1451948	total: 775ms	remaining: 5.2s
7:	learn: 1.1364368	total: 879ms	remaining: 5.05s
8:	learn: 1.1261442	total: 989ms	remaining: 4.94s
9:	learn: 1.1168240	total: 1.1s	remaining: 4.85s
10:	learn: 1.1104823	total: 1.21s	remaining: 4.73s
11:	learn: 1.1049322	total: 1.32s	remaining: 4.62s
12:	learn: 1.0976468	total: 1.43s	remaining: 4.51s
13:	learn: 1.0897076	total: 1.53s	remaining: 4.38s
14:	learn: 1.0823774	total: 1.65s	remaining: 4.29s
15:	learn: 1.0760213	total: 1.74s	remaining: 4.14s
16:	learn: 1.0694210	total: 1.83s	remaining: 3.99s
17:	learn: 1.0635973	total: 1.95s	remaining: 3.9s
18:	learn: 1.0575546	total: 2.05s	remaining: 3.77s
19:	learn: 1.0518189	total: 2.16s	remaining: 3.67s
20:	learn: 1.0465214	total: 2.27s	remaining: 3.57s
21:	learn: 1.0418874	total: 2.38s	remaining: 3.46s
22:	learn: 1.0377409	total: 2.47s	remaining: 3.33s
23:	learn: 1.0332723	total: 2.57s	remaining: 3.22s
24:	learn: 1.0277571	total: 2.71s	remaining: 3.15s
25:	learn: 1.0232594	total: 2.83s	remaining: 3.05s
26:	learn: 1.0185210	total: 2.94s	remaining: 2.94s
27:	learn: 1.0143851	total: 3.04s	remaining: 2.82s
28:	learn: 1.0100265	total: 3.14s	remaining: 2.71s
29:	learn: 1.0050968	total: 3.24s	remaining: 2.59s
30:	learn: 1.0012075	total: 3.35s	remaining: 2.49s
31:	learn: 0.9974158	total: 3.46s	remaining: 2.38s
32:	learn: 0.9939280	total: 3.57s	remaining: 2.27s
33:	learn: 0.9906709	total: 3.68s	remaining: 2.17s
34:	learn: 0.9872026	total: 3.78s	remaining: 2.05s
35:	learn: 0.9842263	total: 3.88s	remaining: 1.94s
36:	learn: 0.9809738	total: 3.98s	remaining: 1.83s
37:	learn: 0.9773787	total: 4.07s	remaining: 1.71s
38:	learn: 0.9744508	total: 4.17s	remaining: 1.61s
39:	learn: 0.9702493	total: 4.28s	remaining: 1.5s
40:	learn: 0.9675374	total: 4.38s	remaining: 1.39s
41:	learn: 0.9639168	total: 4.47s	remaining: 1.28s
42:	learn: 0.9609832	total: 4.57s	remaining: 1.17s
43:	learn: 0.9581557	total: 4.66s	remaining: 1.06s
44:	learn: 0.9554032	total: 4.82s	remaining: 964ms
45:	learn: 0.9527416	total: 4.98s	remaining: 866ms
46:	learn: 0.9487603	total: 5.12s	remaining: 763ms
47:	learn: 0.9462179	total: 5.3s	remaining: 662ms
48:	learn: 0.9430606	total: 5.5s	remaining: 561ms
49:	learn: 0.9405876	total: 5.69s	remaining: 455ms
50:	learn: 0.9376860	total: 6.06s	remaining: 356ms
51:	learn: 0.9357030	total: 6.64s	remaining: 255ms
52:	learn: 0.9329068	total: 6.95s	remaining: 131ms

[I 2025-10-10 20:01:34,859] Trial 7 finished with value: 0.8745668007456197 and parameters: {'iterations': 54, 'depth': 8, 'learning_rate': 0.05916755558969498}. Best is trial 4 with value: 0.6864084186774555.

53:	learn: 0.9304333	total: 7.15s	remaining: 0us
Trial 7: RMSE=0.8746, R2=0.4069
0:	learn: 1.2114117	total: 51.2ms	remaining: 3.59s
1:	learn: 1.2026263	total: 97.9ms	remaining: 3.38s
2:	learn: 1.1918919	total: 165ms	remaining: 3.74s
3:	learn: 1.1819550	total: 214ms	remaining: 3.59s
4:	learn: 1.1742010	total: 263ms	remaining: 3.48s
5:	learn: 1.1668226	total: 315ms	remaining: 3.41s
6:	learn: 1.1577079	total: 363ms	remaining: 3.32s
7:	learn: 1.1502842	total: 413ms	remaining: 3.25s
8:	learn: 1.1407630	total: 463ms	remaining: 3.19s
9:	learn: 1.1349520	total: 517ms	remaining: 3.16s
10:	learn: 1.1292103	total: 568ms	remaining: 3.1s
11:	learn: 1.1224976	total: 613ms	remaining: 3.01s
12:	learn: 1.1169584	total: 658ms	remaining: 2.93s
13:	learn: 1.1111964	total: 702ms	remaining: 2.86s
14:	learn: 1.1064926	total: 752ms	remaining: 2.81s
15:	learn: 1.0994032	total: 802ms	remaining: 2.76s
16:	learn: 1.0931941	total: 848ms	remaining: 2.69s
17:	learn: 1.0878107	total: 892ms	remaining: 2.63s
18:	learn: 1.0824844	total: 939ms	remaining: 2.57s
19:	learn: 1.0783943	total: 985ms	remaining: 2.51s
20:	learn: 1.0742537	total: 1.03s	remaining: 2.46s
21:	learn: 1.0696597	total: 1.08s	remaining: 2.4s
22:	learn: 1.0652158	total: 1.12s	remaining: 2.35s
23:	learn: 1.0612507	total: 1.2s	remaining: 2.34s
24:	learn: 1.0579331	total: 1.24s	remaining: 2.29s
25:	learn: 1.0532078	total: 1.29s	remaining: 2.24s
26:	learn: 1.0492971	total: 1.34s	remaining: 2.18s
27:	learn: 1.0460776	total: 1.38s	remaining: 2.13s
28:	learn: 1.0421015	total: 1.43s	remaining: 2.08s
29:	learn: 1.0385853	total: 1.48s	remaining: 2.03s
30:	learn: 1.0348530	total: 1.53s	remaining: 1.97s
31:	learn: 1.0317456	total: 1.57s	remaining: 1.92s
32:	learn: 1.0291879	total: 1.61s	remaining: 1.86s
33:	learn: 1.0262841	total: 1.66s	remaining: 1.81s
34:	learn: 1.0233172	total: 1.71s	remaining: 1.75s
35:	learn: 1.0203770	total: 1.75s	remaining: 1.7s
36:	learn: 1.0163556	total: 1.79s	remaining: 1.65s
37:	learn: 1.0134832	total: 1.84s	remaining: 1.6s
38:	learn: 1.0109488	total: 1.9s	remaining: 1.55s
39:	learn: 1.0081617	total: 1.94s	remaining: 1.5s
40:	learn: 1.0053900	total: 1.99s	remaining: 1.45s
41:	learn: 1.0029642	total: 2.03s	remaining: 1.4s
42:	learn: 1.0003641	total: 2.08s	remaining: 1.35s
43:	learn: 0.9967864	total: 2.12s	remaining: 1.3s
44:	learn: 0.9938250	total: 2.17s	remaining: 1.25s
45:	learn: 0.9913088	total: 2.22s	remaining: 1.2s
46:	learn: 0.9893566	total: 2.27s	remaining: 1.16s
47:	learn: 0.9869840	total: 2.33s	remaining: 1.11s
48:	learn: 0.9837031	total: 2.37s	remaining: 1.06s
49:	learn: 0.9815183	total: 2.42s	remaining: 1.01s
50:	learn: 0.9795527	total: 2.46s	remaining: 967ms
51:	learn: 0.9772120	total: 2.51s	remaining: 917ms
52:	learn: 0.9745045	total: 2.55s	remaining: 868ms
53:	learn: 0.9721031	total: 2.6s	remaining: 820ms
54:	learn: 0.9703692	total: 2.65s	remaining: 770ms
55:	learn: 0.9680567	total: 2.69s	remaining: 722ms
56:	learn: 0.9658465	total: 2.74s	remaining: 672ms
57:	learn: 0.9635890	total: 2.78s	remaining: 624ms
58:	learn: 0.9617259	total: 2.82s	remaining: 574ms
59:	learn: 0.9599944	total: 2.87s	remaining: 527ms
60:	learn: 0.9578503	total: 2.92s	remaining: 478ms
61:	learn: 0.9558835	total: 2.97s	remaining: 431ms
62:	learn: 0.9543657	total: 3.01s	remaining: 383ms
63:	learn: 0.9524064	total: 3.06s	remaining: 335ms
64:	learn: 0.9502378	total: 3.1s	remaining: 286ms
65:	learn: 0.9487212	total: 3.14s	remaining: 238ms
66:	learn: 0.9465889	total: 3.18s	remaining: 190ms
67:	learn: 0.9449252	total: 3.23s	remaining: 143ms
68:	learn: 0.9424938	total: 3.3s	remaining: 95.6ms
69:	learn: 0.9409427	total: 3.35s	remaining: 47.9ms
70:	learn: 0.9395295	total: 3.4s	remaining: 0us

[I 2025-10-10 20:01:43,198] Trial 8 finished with value: 0.8871040423378561 and parameters: {'iterations': 71, 'depth': 6, 'learning_rate': 0.06710016630991077}. Best is trial 4 with value: 0.6864084186774555.

Trial 8: RMSE=0.8871, R2=0.3984
0:	learn: 1.2171728	total: 270ms	remaining: 24.3s
1:	learn: 1.2127840	total: 579ms	remaining: 25.8s
2:	learn: 1.2081724	total: 882ms	remaining: 25.9s
3:	learn: 1.2033234	total: 1.19s	remaining: 25.9s
4:	learn: 1.1986134	total: 1.52s	remaining: 26.2s
5:	learn: 1.1941902	total: 1.81s	remaining: 25.6s
6:	learn: 1.1902335	total: 2.06s	remaining: 24.8s
7:	learn: 1.1859102	total: 2.4s	remaining: 24.9s
8:	learn: 1.1819206	total: 2.72s	remaining: 24.8s
9:	learn: 1.1782136	total: 3.05s	remaining: 24.7s
10:	learn: 1.1744756	total: 3.4s	remaining: 24.7s
11:	learn: 1.1705655	total: 3.7s	remaining: 24.4s
12:	learn: 1.1664986	total: 4.41s	remaining: 26.5s
13:	learn: 1.1634194	total: 4.81s	remaining: 26.4s
14:	learn: 1.1599410	total: 4.99s	remaining: 25.3s
15:	learn: 1.1564622	total: 5.14s	remaining: 24.1s
16:	learn: 1.1528912	total: 5.31s	remaining: 23.1s
17:	learn: 1.1497414	total: 5.47s	remaining: 22.2s
18:	learn: 1.1464524	total: 5.66s	remaining: 21.5s
19:	learn: 1.1424073	total: 5.84s	remaining: 20.7s
20:	learn: 1.1396180	total: 6.02s	remaining: 20.1s
21:	learn: 1.1361438	total: 6.2s	remaining: 19.4s
22:	learn: 1.1331264	total: 6.35s	remaining: 18.8s
23:	learn: 1.1296196	total: 6.52s	remaining: 18.2s
24:	learn: 1.1267193	total: 6.73s	remaining: 17.8s
25:	learn: 1.1234801	total: 6.93s	remaining: 17.3s
26:	learn: 1.1208711	total: 7.11s	remaining: 16.8s
27:	learn: 1.1180607	total: 7.3s	remaining: 16.4s
28:	learn: 1.1144138	total: 7.5s	remaining: 16s
29:	learn: 1.1112467	total: 7.69s	remaining: 15.6s
30:	learn: 1.1083074	total: 7.87s	remaining: 15.2s
31:	learn: 1.1041579	total: 8.07s	remaining: 14.9s
32:	learn: 1.1010409	total: 8.27s	remaining: 14.5s
33:	learn: 1.0987426	total: 8.46s	remaining: 14.2s
34:	learn: 1.0957470	total: 8.65s	remaining: 13.8s
35:	learn: 1.0929491	total: 8.87s	remaining: 13.5s
36:	learn: 1.0907639	total: 9.05s	remaining: 13.2s
37:	learn: 1.0878636	total: 9.21s	remaining: 12.8s
38:	learn: 1.0854480	total: 9.37s	remaining: 12.5s
39:	learn: 1.0827516	total: 9.54s	remaining: 12.2s
40:	learn: 1.0800642	total: 9.71s	remaining: 11.8s
41:	learn: 1.0775796	total: 9.9s	remaining: 11.5s
42:	learn: 1.0751729	total: 10.1s	remaining: 11.2s
43:	learn: 1.0722646	total: 10.2s	remaining: 10.9s
44:	learn: 1.0697366	total: 10.4s	remaining: 10.6s
45:	learn: 1.0674059	total: 10.6s	remaining: 10.3s
46:	learn: 1.0649215	total: 10.7s	remaining: 10.1s
47:	learn: 1.0630867	total: 10.9s	remaining: 9.79s
48:	learn: 1.0608367	total: 11.1s	remaining: 9.51s
49:	learn: 1.0584814	total: 11.3s	remaining: 9.23s
50:	learn: 1.0564565	total: 11.4s	remaining: 8.95s
51:	learn: 1.0543006	total: 11.6s	remaining: 8.69s
52:	learn: 1.0517854	total: 11.8s	remaining: 8.44s
53:	learn: 1.0492322	total: 12s	remaining: 8.22s
54:	learn: 1.0469487	total: 12.2s	remaining: 7.97s
55:	learn: 1.0446534	total: 12.3s	remaining: 7.71s
56:	learn: 1.0423698	total: 12.5s	remaining: 7.46s
57:	learn: 1.0404731	total: 12.7s	remaining: 7.22s
58:	learn: 1.0386237	total: 12.9s	remaining: 7s
59:	learn: 1.0369439	total: 13.1s	remaining: 6.77s
60:	learn: 1.0349369	total: 13.3s	remaining: 6.54s
61:	learn: 1.0332930	total: 13.5s	remaining: 6.31s
62:	learn: 1.0307635	total: 13.7s	remaining: 6.08s
63:	learn: 1.0286986	total: 13.8s	remaining: 5.84s
64:	learn: 1.0268381	total: 14s	remaining: 5.61s
65:	learn: 1.0250214	total: 14.2s	remaining: 5.38s
66:	learn: 1.0226780	total: 14.4s	remaining: 5.14s
67:	learn: 1.0208397	total: 14.5s	remaining: 4.91s
68:	learn: 1.0187332	total: 14.7s	remaining: 4.7s
69:	learn: 1.0169122	total: 15.1s	remaining: 4.51s
70:	learn: 1.0153442	total: 15.4s	remaining: 4.33s
71:	learn: 1.0137031	total: 15.7s	remaining: 4.14s
72:	learn: 1.0115640	total: 16s	remaining: 3.94s
73:	learn: 1.0098592	total: 16.2s	remaining: 3.73s
74:	learn: 1.0079647	total: 16.5s	remaining: 3.52s
75:	learn: 1.0065290	total: 16.8s	remaining: 3.32s
76:	learn: 1.0052382	total: 17.2s	remaining: 3.12s
77:	learn: 1.0030945	total: 17.4s	remaining: 2.91s
78:	learn: 1.0016197	total: 17.7s	remaining: 2.69s
79:	learn: 1.0002591	total: 18s	remaining: 2.48s
80:	learn: 0.9989511	total: 18.4s	remaining: 2.27s
81:	learn: 0.9973096	total: 18.7s	remaining: 2.05s
82:	learn: 0.9957945	total: 19s	remaining: 1.83s
83:	learn: 0.9944748	total: 19.2s	remaining: 1.6s
84:	learn: 0.9928327	total: 19.4s	remaining: 1.37s
85:	learn: 0.9910069	total: 19.6s	remaining: 1.14s
86:	learn: 0.9888977	total: 19.8s	remaining: 910ms
87:	learn: 0.9874937	total: 20s	remaining: 681ms
88:	learn: 0.9862307	total: 20.2s	remaining: 453ms
89:	learn: 0.9842000	total: 20.4s	remaining: 226ms

[I 2025-10-10 20:02:07,925] Trial 9 finished with value: 0.9713251949415345 and parameters: {'iterations': 91, 'depth': 9, 'learning_rate': 0.019128585196600018}. Best is trial 4 with value: 0.6864084186774555.

90:	learn: 0.9823445	total: 20.6s	remaining: 0us
Trial 9: RMSE=0.9713, R2=0.3413
0:	learn: 1.1949435	total: 358ms	remaining: 24s
1:	learn: 1.1697113	total: 708ms	remaining: 23.4s
2:	learn: 1.1455050	total: 1.07s	remaining: 23.1s
3:	learn: 1.1244398	total: 1.43s	remaining: 22.9s
4:	learn: 1.1075744	total: 1.77s	remaining: 22.4s
5:	learn: 1.0893700	total: 2.13s	remaining: 22s
6:	learn: 1.0747777	total: 2.48s	remaining: 21.7s
7:	learn: 1.0607428	total: 2.84s	remaining: 21.3s
8:	learn: 1.0473669	total: 3.21s	remaining: 21s
9:	learn: 1.0354013	total: 3.56s	remaining: 20.6s
10:	learn: 1.0232883	total: 3.91s	remaining: 20.2s
11:	learn: 1.0131023	total: 4.27s	remaining: 19.9s
12:	learn: 1.0013075	total: 4.76s	remaining: 20.2s
13:	learn: 0.9892312	total: 5.36s	remaining: 20.7s
14:	learn: 0.9792885	total: 5.96s	remaining: 21s
15:	learn: 0.9711041	total: 6.54s	remaining: 21.2s
16:	learn: 0.9630615	total: 7.15s	remaining: 21.4s
17:	learn: 0.9556894	total: 7.79s	remaining: 21.7s
18:	learn: 0.9471939	total: 8.39s	remaining: 21.6s
19:	learn: 0.9401439	total: 8.91s	remaining: 21.4s
20:	learn: 0.9341115	total: 9.26s	remaining: 20.7s
21:	learn: 0.9267369	total: 9.6s	remaining: 20.1s
22:	learn: 0.9200991	total: 9.97s	remaining: 19.5s
23:	learn: 0.9132039	total: 10.3s	remaining: 18.9s
24:	learn: 0.9053580	total: 10.7s	remaining: 18.4s
25:	learn: 0.9002388	total: 11s	remaining: 17.8s
26:	learn: 0.8956069	total: 11.4s	remaining: 17.3s
27:	learn: 0.8888139	total: 11.7s	remaining: 16.8s
28:	learn: 0.8832996	total: 12.1s	remaining: 16.3s
29:	learn: 0.8759395	total: 12.5s	remaining: 15.8s
30:	learn: 0.8695598	total: 12.8s	remaining: 15.3s
31:	learn: 0.8662576	total: 13.2s	remaining: 14.8s
32:	learn: 0.8616391	total: 13.5s	remaining: 14.3s
33:	learn: 0.8555021	total: 13.9s	remaining: 13.9s
34:	learn: 0.8504282	total: 14.2s	remaining: 13.4s
35:	learn: 0.8463992	total: 14.6s	remaining: 13s
36:	learn: 0.8404627	total: 14.9s	remaining: 12.5s
37:	learn: 0.8366048	total: 15.3s	remaining: 12.1s
38:	learn: 0.8330944	total: 15.7s	remaining: 11.6s
39:	learn: 0.8295134	total: 16s	remaining: 11.2s
40:	learn: 0.8238953	total: 16.4s	remaining: 10.8s
41:	learn: 0.8183102	total: 16.7s	remaining: 10.4s
42:	learn: 0.8142263	total: 17.1s	remaining: 9.94s
43:	learn: 0.8112329	total: 17.4s	remaining: 9.51s
44:	learn: 0.8077322	total: 17.8s	remaining: 9.09s
45:	learn: 0.8037996	total: 18.2s	remaining: 8.69s
46:	learn: 0.7995015	total: 18.5s	remaining: 8.27s
47:	learn: 0.7937396	total: 18.9s	remaining: 7.86s
48:	learn: 0.7903676	total: 19.4s	remaining: 7.51s
49:	learn: 0.7879078	total: 20s	remaining: 7.18s
50:	learn: 0.7856044	total: 20.6s	remaining: 6.86s
51:	learn: 0.7820866	total: 21.1s	remaining: 6.5s
52:	learn: 0.7778998	total: 21.8s	remaining: 6.16s
53:	learn: 0.7733305	total: 22.4s	remaining: 5.8s
54:	learn: 0.7694199	total: 22.9s	remaining: 5.42s
55:	learn: 0.7652892	total: 23.5s	remaining: 5.04s
56:	learn: 0.7621835	total: 23.9s	remaining: 4.61s
57:	learn: 0.7595017	total: 24.2s	remaining: 4.18s
58:	learn: 0.7559401	total: 24.6s	remaining: 3.75s
59:	learn: 0.7527466	total: 24.9s	remaining: 3.33s
60:	learn: 0.7509243	total: 25.3s	remaining: 2.9s
61:	learn: 0.7476950	total: 25.6s	remaining: 2.48s
62:	learn: 0.7432410	total: 26s	remaining: 2.06s
63:	learn: 0.7383509	total: 26.4s	remaining: 1.65s
64:	learn: 0.7349152	total: 26.7s	remaining: 1.23s
65:	learn: 0.7304041	total: 27.1s	remaining: 822ms
66:	learn: 0.7281311	total: 27.5s	remaining: 410ms

[I 2025-10-10 20:02:39,951] Trial 10 finished with value: 0.545086205552607 and parameters: {'iterations': 68, 'depth': 10, 'learning_rate': 0.09868370473288476}. Best is trial 10 with value: 0.545086205552607.

67:	learn: 0.7248398	total: 27.8s	remaining: 0us
Trial 10: RMSE=0.5451, R2=0.6303
0:	learn: 1.1961542	total: 364ms	remaining: 24.4s
1:	learn: 1.1719498	total: 711ms	remaining: 23.5s
2:	learn: 1.1486415	total: 1.06s	remaining: 23.1s
3:	learn: 1.1282144	total: 1.44s	remaining: 23s
4:	learn: 1.1113947	total: 1.91s	remaining: 24s
5:	learn: 1.0940839	total: 2.51s	remaining: 25.9s
6:	learn: 1.0803451	total: 3.12s	remaining: 27.2s
7:	learn: 1.0658040	total: 3.65s	remaining: 27.3s
8:	learn: 1.0502557	total: 4.18s	remaining: 27.4s
9:	learn: 1.0366367	total: 4.81s	remaining: 27.9s
10:	learn: 1.0251633	total: 5.39s	remaining: 27.9s
11:	learn: 1.0152367	total: 5.94s	remaining: 27.7s
12:	learn: 1.0035450	total: 6.43s	remaining: 27.2s
13:	learn: 0.9943779	total: 6.8s	remaining: 26.2s
14:	learn: 0.9867198	total: 7.16s	remaining: 25.3s
15:	learn: 0.9782089	total: 7.51s	remaining: 24.4s
16:	learn: 0.9670332	total: 7.88s	remaining: 23.6s
17:	learn: 0.9599955	total: 8.22s	remaining: 22.8s
18:	learn: 0.9533268	total: 8.57s	remaining: 22.1s
19:	learn: 0.9442230	total: 8.94s	remaining: 21.5s
20:	learn: 0.9379723	total: 9.29s	remaining: 20.8s
21:	learn: 0.9309023	total: 9.64s	remaining: 20.2s
22:	learn: 0.9240246	total: 10s	remaining: 19.6s
23:	learn: 0.9165751	total: 10.4s	remaining: 19s
24:	learn: 0.9084492	total: 10.7s	remaining: 18.4s
25:	learn: 0.9021507	total: 11.1s	remaining: 17.9s
26:	learn: 0.8979080	total: 11.4s	remaining: 17.4s
27:	learn: 0.8920617	total: 11.8s	remaining: 16.8s
28:	learn: 0.8867028	total: 12.1s	remaining: 16.3s
29:	learn: 0.8825102	total: 12.5s	remaining: 15.8s
30:	learn: 0.8757671	total: 12.8s	remaining: 15.3s
31:	learn: 0.8708955	total: 13.2s	remaining: 14.9s
32:	learn: 0.8672200	total: 13.6s	remaining: 14.4s
33:	learn: 0.8604810	total: 13.9s	remaining: 13.9s
34:	learn: 0.8535555	total: 14.3s	remaining: 13.5s
35:	learn: 0.8490609	total: 14.6s	remaining: 13s
36:	learn: 0.8444042	total: 15s	remaining: 12.5s
37:	learn: 0.8407358	total: 15.3s	remaining: 12.1s
38:	learn: 0.8366506	total: 15.7s	remaining: 11.7s
39:	learn: 0.8321440	total: 16s	remaining: 11.2s
40:	learn: 0.8264954	total: 16.5s	remaining: 10.8s
41:	learn: 0.8218337	total: 17s	remaining: 10.6s
42:	learn: 0.8168910	total: 17.7s	remaining: 10.3s
43:	learn: 0.8128712	total: 18.2s	remaining: 9.93s
44:	learn: 0.8088283	total: 18.7s	remaining: 9.57s
45:	learn: 0.8054931	total: 19.3s	remaining: 9.24s
46:	learn: 0.8017285	total: 20s	remaining: 8.92s
47:	learn: 0.7994298	total: 20.6s	remaining: 8.58s
48:	learn: 0.7958708	total: 21.1s	remaining: 8.17s
49:	learn: 0.7923330	total: 21.4s	remaining: 7.71s
50:	learn: 0.7891776	total: 21.8s	remaining: 7.26s
51:	learn: 0.7846683	total: 22.1s	remaining: 6.81s
52:	learn: 0.7820557	total: 22.5s	remaining: 6.37s
53:	learn: 0.7782731	total: 22.9s	remaining: 5.92s
54:	learn: 0.7739095	total: 23.2s	remaining: 5.48s
55:	learn: 0.7715981	total: 23.5s	remaining: 5.05s
56:	learn: 0.7679953	total: 23.9s	remaining: 4.62s
57:	learn: 0.7643389	total: 24.3s	remaining: 4.18s
58:	learn: 0.7594217	total: 24.6s	remaining: 3.75s
59:	learn: 0.7561780	total: 25s	remaining: 3.33s
60:	learn: 0.7546714	total: 25.4s	remaining: 2.91s
61:	learn: 0.7493554	total: 25.7s	remaining: 2.49s
62:	learn: 0.7447531	total: 26.1s	remaining: 2.07s
63:	learn: 0.7412738	total: 26.4s	remaining: 1.65s
64:	learn: 0.7369996	total: 26.8s	remaining: 1.24s
65:	learn: 0.7344231	total: 27.2s	remaining: 823ms
66:	learn: 0.7326366	total: 27.5s	remaining: 411ms

[I 2025-10-10 20:03:11,969] Trial 11 finished with value: 0.5499592964984511 and parameters: {'iterations': 68, 'depth': 10, 'learning_rate': 0.09410426949599114}. Best is trial 10 with value: 0.545086205552607.

67:	learn: 0.7283502	total: 27.9s	remaining: 0us
Trial 11: RMSE=0.5500, R2=0.6270
0:	learn: 1.1951674	total: 534ms	remaining: 34.2s
1:	learn: 1.1701245	total: 1.11s	remaining: 35s
2:	learn: 1.1460830	total: 1.7s	remaining: 35.2s
3:	learn: 1.1251339	total: 2.26s	remaining: 34.5s
4:	learn: 1.1083584	total: 2.76s	remaining: 33.1s
5:	learn: 1.0902576	total: 3.3s	remaining: 32.5s
6:	learn: 1.0770692	total: 3.66s	remaining: 30.3s
7:	learn: 1.0618520	total: 4.01s	remaining: 28.5s
8:	learn: 1.0489456	total: 4.37s	remaining: 27.2s
9:	learn: 1.0372731	total: 4.72s	remaining: 26s
10:	learn: 1.0270093	total: 5.08s	remaining: 24.9s
11:	learn: 1.0158203	total: 5.44s	remaining: 24s
12:	learn: 1.0008354	total: 5.79s	remaining: 23.2s
13:	learn: 0.9888517	total: 6.16s	remaining: 22.4s
14:	learn: 0.9789899	total: 6.5s	remaining: 21.7s
15:	learn: 0.9707375	total: 6.86s	remaining: 21s
16:	learn: 0.9604469	total: 7.23s	remaining: 20.4s
17:	learn: 0.9535129	total: 7.58s	remaining: 19.8s
18:	learn: 0.9450584	total: 7.92s	remaining: 19.2s
19:	learn: 0.9385089	total: 8.29s	remaining: 18.7s
20:	learn: 0.9313314	total: 8.65s	remaining: 18.1s
21:	learn: 0.9231433	total: 9s	remaining: 17.6s
22:	learn: 0.9161434	total: 9.37s	remaining: 17.1s
23:	learn: 0.9080373	total: 9.72s	remaining: 16.6s
24:	learn: 0.9028673	total: 10.1s	remaining: 16.1s
25:	learn: 0.8971117	total: 10.4s	remaining: 15.7s
26:	learn: 0.8922945	total: 10.8s	remaining: 15.2s
27:	learn: 0.8866634	total: 11.1s	remaining: 14.7s
28:	learn: 0.8799743	total: 11.5s	remaining: 14.3s
29:	learn: 0.8742191	total: 11.9s	remaining: 13.8s
30:	learn: 0.8695823	total: 12.2s	remaining: 13.4s
31:	learn: 0.8632374	total: 12.6s	remaining: 13s
32:	learn: 0.8588050	total: 12.9s	remaining: 12.5s
33:	learn: 0.8527812	total: 13.3s	remaining: 12.1s
34:	learn: 0.8444090	total: 13.9s	remaining: 11.9s
35:	learn: 0.8395229	total: 14.5s	remaining: 11.7s
36:	learn: 0.8345002	total: 15.1s	remaining: 11.4s
37:	learn: 0.8301280	total: 15.7s	remaining: 11.1s
38:	learn: 0.8261867	total: 16.3s	remaining: 10.9s
39:	learn: 0.8199002	total: 16.9s	remaining: 10.6s
40:	learn: 0.8151337	total: 17.5s	remaining: 10.2s
41:	learn: 0.8114361	total: 17.9s	remaining: 9.82s
42:	learn: 0.8050539	total: 18.3s	remaining: 9.36s
43:	learn: 0.8005608	total: 18.7s	remaining: 8.9s
44:	learn: 0.7971111	total: 19s	remaining: 8.45s
45:	learn: 0.7932954	total: 19.4s	remaining: 8s
46:	learn: 0.7891979	total: 19.7s	remaining: 7.55s
47:	learn: 0.7839541	total: 20.1s	remaining: 7.12s
48:	learn: 0.7802496	total: 20.5s	remaining: 6.68s
49:	learn: 0.7781352	total: 20.8s	remaining: 6.24s
50:	learn: 0.7753607	total: 21.2s	remaining: 5.81s
51:	learn: 0.7719533	total: 21.5s	remaining: 5.38s
52:	learn: 0.7688982	total: 21.9s	remaining: 4.96s
53:	learn: 0.7661870	total: 22.3s	remaining: 4.53s
54:	learn: 0.7611186	total: 22.6s	remaining: 4.12s
55:	learn: 0.7571115	total: 23s	remaining: 3.69s
56:	learn: 0.7543364	total: 23.4s	remaining: 3.28s
57:	learn: 0.7508645	total: 23.7s	remaining: 2.86s
58:	learn: 0.7484128	total: 24.1s	remaining: 2.45s
59:	learn: 0.7455591	total: 24.4s	remaining: 2.04s
60:	learn: 0.7434064	total: 24.8s	remaining: 1.63s
61:	learn: 0.7400405	total: 25.1s	remaining: 1.22s
62:	learn: 0.7373143	total: 25.5s	remaining: 810ms
63:	learn: 0.7339781	total: 25.9s	remaining: 404ms

[I 2025-10-10 20:03:42,994] Trial 12 finished with value: 0.5541592882618093 and parameters: {'iterations': 65, 'depth': 10, 'learning_rate': 0.09783548854693687}. Best is trial 10 with value: 0.545086205552607.

64:	learn: 0.7319712	total: 26.2s	remaining: 0us
Trial 12: RMSE=0.5542, R2=0.6242
0:	learn: 1.2042629	total: 132ms	remaining: 3.82s
1:	learn: 1.1873756	total: 260ms	remaining: 3.64s
2:	learn: 1.1737390	total: 331ms	remaining: 2.98s
3:	learn: 1.1564769	total: 401ms	remaining: 2.61s
4:	learn: 1.1441204	total: 466ms	remaining: 2.33s
5:	learn: 1.1308774	total: 540ms	remaining: 2.16s
6:	learn: 1.1188501	total: 609ms	remaining: 2s
7:	learn: 1.1093008	total: 673ms	remaining: 1.85s
8:	learn: 1.0986185	total: 736ms	remaining: 1.72s
9:	learn: 1.0904457	total: 807ms	remaining: 1.61s
10:	learn: 1.0824985	total: 871ms	remaining: 1.5s
11:	learn: 1.0728555	total: 934ms	remaining: 1.4s
12:	learn: 1.0655161	total: 1.02s	remaining: 1.34s
13:	learn: 1.0580852	total: 1.09s	remaining: 1.24s
14:	learn: 1.0505817	total: 1.15s	remaining: 1.15s
15:	learn: 1.0433321	total: 1.21s	remaining: 1.06s
16:	learn: 1.0377042	total: 1.27s	remaining: 975ms
17:	learn: 1.0314341	total: 1.34s	remaining: 891ms
18:	learn: 1.0243327	total: 1.4s	remaining: 808ms
19:	learn: 1.0193372	total: 1.46s	remaining: 729ms
20:	learn: 1.0136642	total: 1.53s	remaining: 655ms
21:	learn: 1.0068672	total: 1.6s	remaining: 581ms
22:	learn: 1.0010640	total: 1.66s	remaining: 505ms
23:	learn: 0.9963281	total: 1.72s	remaining: 431ms
24:	learn: 0.9910986	total: 1.78s	remaining: 357ms
25:	learn: 0.9846902	total: 1.85s	remaining: 285ms
26:	learn: 0.9790006	total: 1.91s	remaining: 212ms
27:	learn: 0.9746483	total: 1.98s	remaining: 141ms

[I 2025-10-10 20:03:50,865] Trial 13 finished with value: 0.9440060667189447 and parameters: {'iterations': 30, 'depth': 7, 'learning_rate': 0.09912734948307467}. Best is trial 10 with value: 0.545086205552607.

28:	learn: 0.9711245	total: 2.05s	remaining: 70.7ms
29:	learn: 0.9676182	total: 2.12s	remaining: 0us
Trial 13: RMSE=0.9440, R2=0.3598
0:	learn: 1.1983755	total: 363ms	remaining: 23.2s
1:	learn: 1.1763498	total: 712ms	remaining: 22.4s
2:	learn: 1.1547525	total: 1.06s	remaining: 22s
3:	learn: 1.1354769	total: 1.44s	remaining: 21.9s
4:	learn: 1.1188871	total: 1.78s	remaining: 21.4s
5:	learn: 1.1055301	total: 2.14s	remaining: 21s
6:	learn: 1.0937032	total: 2.51s	remaining: 20.8s
7:	learn: 1.0764660	total: 2.86s	remaining: 20.4s
8:	learn: 1.0651859	total: 3.2s	remaining: 19.9s
9:	learn: 1.0551064	total: 3.58s	remaining: 19.7s
10:	learn: 1.0418288	total: 3.92s	remaining: 19.3s
11:	learn: 1.0327224	total: 4.38s	remaining: 19.4s
12:	learn: 1.0211944	total: 4.92s	remaining: 19.7s
13:	learn: 1.0126044	total: 5.55s	remaining: 20.2s
14:	learn: 1.0033034	total: 6.11s	remaining: 20.4s
15:	learn: 0.9945035	total: 6.73s	remaining: 20.6s
16:	learn: 0.9844363	total: 7.33s	remaining: 20.7s
17:	learn: 0.9773462	total: 7.95s	remaining: 20.8s
18:	learn: 0.9713690	total: 8.54s	remaining: 20.7s
19:	learn: 0.9635315	total: 8.91s	remaining: 20s
20:	learn: 0.9545624	total: 9.25s	remaining: 19.4s
21:	learn: 0.9485150	total: 9.59s	remaining: 18.7s
22:	learn: 0.9406605	total: 9.97s	remaining: 18.2s
23:	learn: 0.9328321	total: 10.3s	remaining: 17.6s
24:	learn: 0.9277115	total: 10.7s	remaining: 17.1s
25:	learn: 0.9221675	total: 11s	remaining: 16.6s
26:	learn: 0.9176905	total: 11.4s	remaining: 16s
27:	learn: 0.9106981	total: 11.7s	remaining: 15.5s
28:	learn: 0.9044220	total: 12.1s	remaining: 15s
29:	learn: 0.8987376	total: 12.5s	remaining: 14.5s
30:	learn: 0.8927592	total: 12.8s	remaining: 14s
31:	learn: 0.8886241	total: 13.2s	remaining: 13.6s
32:	learn: 0.8836522	total: 13.5s	remaining: 13.1s
33:	learn: 0.8768095	total: 13.9s	remaining: 12.7s
34:	learn: 0.8708624	total: 14.2s	remaining: 12.2s
35:	learn: 0.8654541	total: 14.6s	remaining: 11.8s
36:	learn: 0.8593636	total: 15s	remaining: 11.3s
37:	learn: 0.8538507	total: 15.4s	remaining: 10.9s
38:	learn: 0.8508381	total: 15.7s	remaining: 10.5s
39:	learn: 0.8474829	total: 16.1s	remaining: 10.1s
40:	learn: 0.8419625	total: 16.4s	remaining: 9.63s
41:	learn: 0.8367555	total: 16.8s	remaining: 9.21s
42:	learn: 0.8334985	total: 17.2s	remaining: 8.79s
43:	learn: 0.8293736	total: 17.5s	remaining: 8.38s
44:	learn: 0.8256965	total: 17.9s	remaining: 7.95s
45:	learn: 0.8207766	total: 18.3s	remaining: 7.54s
46:	learn: 0.8166897	total: 18.6s	remaining: 7.14s
47:	learn: 0.8132553	total: 19.2s	remaining: 6.81s
48:	learn: 0.8102951	total: 19.7s	remaining: 6.44s
49:	learn: 0.8061907	total: 20.3s	remaining: 6.1s
50:	learn: 0.8035259	total: 20.9s	remaining: 5.73s
51:	learn: 0.8000960	total: 21.5s	remaining: 5.38s
52:	learn: 0.7973626	total: 22.1s	remaining: 5.01s
53:	learn: 0.7932456	total: 22.7s	remaining: 4.61s
54:	learn: 0.7885331	total: 23.2s	remaining: 4.22s
55:	learn: 0.7841582	total: 23.6s	remaining: 3.79s
56:	learn: 0.7799345	total: 24s	remaining: 3.36s
57:	learn: 0.7771935	total: 24.3s	remaining: 2.93s
58:	learn: 0.7745241	total: 24.6s	remaining: 2.51s
59:	learn: 0.7720815	total: 25s	remaining: 2.08s
60:	learn: 0.7702011	total: 25.4s	remaining: 1.66s
61:	learn: 0.7650467	total: 25.7s	remaining: 1.24s
62:	learn: 0.7623806	total: 26.1s	remaining: 828ms
63:	learn: 0.7603531	total: 26.4s	remaining: 413ms

[I 2025-10-10 20:04:21,815] Trial 14 finished with value: 0.5912663412457874 and parameters: {'iterations': 65, 'depth': 10, 'learning_rate': 0.08574779788592603}. Best is trial 10 with value: 0.545086205552607.

64:	learn: 0.7569273	total: 26.8s	remaining: 0us
Trial 14: RMSE=0.5913, R2=0.5990
0:	learn: 1.2133498	total: 96.6ms	remaining: 3.19s
1:	learn: 1.2033436	total: 223ms	remaining: 3.56s
2:	learn: 1.1946012	total: 323ms	remaining: 3.33s
3:	learn: 1.1869834	total: 424ms	remaining: 3.18s
4:	learn: 1.1797015	total: 525ms	remaining: 3.05s
5:	learn: 1.1725550	total: 632ms	remaining: 2.95s
6:	learn: 1.1661951	total: 732ms	remaining: 2.82s
7:	learn: 1.1587120	total: 827ms	remaining: 2.69s
8:	learn: 1.1520666	total: 923ms	remaining: 2.56s
9:	learn: 1.1443252	total: 1.02s	remaining: 2.46s
10:	learn: 1.1374012	total: 1.12s	remaining: 2.33s
11:	learn: 1.1320824	total: 1.24s	remaining: 2.27s
12:	learn: 1.1264144	total: 1.33s	remaining: 2.16s
13:	learn: 1.1209825	total: 1.43s	remaining: 2.05s
14:	learn: 1.1145229	total: 1.54s	remaining: 1.95s
15:	learn: 1.1087163	total: 1.64s	remaining: 1.84s
16:	learn: 1.1036826	total: 1.73s	remaining: 1.73s
17:	learn: 1.0987273	total: 1.83s	remaining: 1.62s
18:	learn: 1.0944979	total: 1.92s	remaining: 1.52s
19:	learn: 1.0896230	total: 2.02s	remaining: 1.41s
20:	learn: 1.0845819	total: 2.12s	remaining: 1.31s
21:	learn: 1.0792151	total: 2.23s	remaining: 1.22s
22:	learn: 1.0754267	total: 2.33s	remaining: 1.12s
23:	learn: 1.0713441	total: 2.49s	remaining: 1.04s
24:	learn: 1.0668394	total: 2.63s	remaining: 947ms
25:	learn: 1.0628581	total: 2.79s	remaining: 859ms
26:	learn: 1.0592037	total: 2.97s	remaining: 770ms
27:	learn: 1.0554619	total: 3.14s	remaining: 673ms
28:	learn: 1.0511543	total: 3.33s	remaining: 575ms
29:	learn: 1.0478182	total: 3.49s	remaining: 465ms
30:	learn: 1.0439635	total: 3.66s	remaining: 354ms
31:	learn: 1.0408605	total: 3.83s	remaining: 239ms
32:	learn: 1.0375926	total: 4s	remaining: 121ms
33:	learn: 1.0342343	total: 4.18s	remaining: 0us

[I 2025-10-10 20:04:30,086] Trial 15 finished with value: 1.07209344466122 and parameters: {'iterations': 34, 'depth': 8, 'learning_rate': 0.04168761043952512}. Best is trial 10 with value: 0.545086205552607.

Trial 15: RMSE=1.0721, R2=0.2729
0:	learn: 1.2149071	total: 27.8ms	remaining: 2.75s
1:	learn: 1.2085591	total: 50.5ms	remaining: 2.48s
2:	learn: 1.2028764	total: 72.6ms	remaining: 2.35s
3:	learn: 1.1951521	total: 96.1ms	remaining: 2.31s
4:	learn: 1.1899168	total: 123ms	remaining: 2.34s
5:	learn: 1.1850030	total: 145ms	remaining: 2.27s
6:	learn: 1.1787704	total: 169ms	remaining: 2.25s
7:	learn: 1.1742824	total: 196ms	remaining: 2.25s
8:	learn: 1.1697645	total: 218ms	remaining: 2.2s
9:	learn: 1.1649025	total: 246ms	remaining: 2.22s
10:	learn: 1.1602778	total: 274ms	remaining: 2.22s
11:	learn: 1.1566767	total: 296ms	remaining: 2.17s
12:	learn: 1.1532713	total: 322ms	remaining: 2.15s
13:	learn: 1.1495567	total: 344ms	remaining: 2.11s
14:	learn: 1.1458909	total: 367ms	remaining: 2.08s
15:	learn: 1.1427277	total: 400ms	remaining: 2.1s
16:	learn: 1.1392184	total: 437ms	remaining: 2.13s
17:	learn: 1.1362072	total: 467ms	remaining: 2.13s
18:	learn: 1.1323160	total: 494ms	remaining: 2.1s
19:	learn: 1.1294693	total: 521ms	remaining: 2.08s
20:	learn: 1.1262202	total: 545ms	remaining: 2.05s
21:	learn: 1.1230397	total: 568ms	remaining: 2.01s
22:	learn: 1.1200906	total: 590ms	remaining: 1.98s
23:	learn: 1.1176379	total: 614ms	remaining: 1.94s
24:	learn: 1.1151592	total: 636ms	remaining: 1.91s
25:	learn: 1.1126474	total: 658ms	remaining: 1.87s
26:	learn: 1.1094550	total: 684ms	remaining: 1.85s
27:	learn: 1.1071636	total: 710ms	remaining: 1.82s
28:	learn: 1.1045383	total: 733ms	remaining: 1.79s
29:	learn: 1.1013966	total: 758ms	remaining: 1.77s
30:	learn: 1.0991302	total: 780ms	remaining: 1.74s
31:	learn: 1.0971454	total: 805ms	remaining: 1.71s
32:	learn: 1.0952224	total: 827ms	remaining: 1.68s
33:	learn: 1.0931382	total: 853ms	remaining: 1.66s
34:	learn: 1.0908451	total: 882ms	remaining: 1.64s
35:	learn: 1.0888988	total: 912ms	remaining: 1.62s
36:	learn: 1.0861722	total: 938ms	remaining: 1.6s
37:	learn: 1.0838546	total: 963ms	remaining: 1.57s
38:	learn: 1.0816068	total: 989ms	remaining: 1.55s
39:	learn: 1.0795518	total: 1.01s	remaining: 1.52s
40:	learn: 1.0776503	total: 1.03s	remaining: 1.49s
41:	learn: 1.0757505	total: 1.06s	remaining: 1.46s
42:	learn: 1.0738628	total: 1.08s	remaining: 1.43s
43:	learn: 1.0723281	total: 1.1s	remaining: 1.4s
44:	learn: 1.0705906	total: 1.13s	remaining: 1.38s
45:	learn: 1.0687165	total: 1.15s	remaining: 1.35s
46:	learn: 1.0666113	total: 1.17s	remaining: 1.32s
47:	learn: 1.0644874	total: 1.2s	remaining: 1.3s
48:	learn: 1.0628612	total: 1.22s	remaining: 1.27s
49:	learn: 1.0612436	total: 1.24s	remaining: 1.24s
50:	learn: 1.0594749	total: 1.26s	remaining: 1.21s
51:	learn: 1.0580038	total: 1.28s	remaining: 1.19s
52:	learn: 1.0565705	total: 1.31s	remaining: 1.16s
53:	learn: 1.0547241	total: 1.33s	remaining: 1.14s
54:	learn: 1.0532122	total: 1.36s	remaining: 1.11s
55:	learn: 1.0515671	total: 1.38s	remaining: 1.08s
56:	learn: 1.0502570	total: 1.4s	remaining: 1.06s
57:	learn: 1.0490439	total: 1.43s	remaining: 1.03s
58:	learn: 1.0475655	total: 1.47s	remaining: 1.02s
59:	learn: 1.0459962	total: 1.49s	remaining: 994ms
60:	learn: 1.0444037	total: 1.52s	remaining: 971ms
61:	learn: 1.0431121	total: 1.54s	remaining: 947ms
62:	learn: 1.0416851	total: 1.57s	remaining: 921ms
63:	learn: 1.0403999	total: 1.59s	remaining: 894ms
64:	learn: 1.0391078	total: 1.61s	remaining: 867ms
65:	learn: 1.0378221	total: 1.63s	remaining: 841ms
66:	learn: 1.0363153	total: 1.65s	remaining: 815ms
67:	learn: 1.0352311	total: 1.68s	remaining: 788ms
68:	learn: 1.0340857	total: 1.7s	remaining: 762ms
69:	learn: 1.0323765	total: 1.72s	remaining: 737ms
70:	learn: 1.0308786	total: 1.74s	remaining: 712ms
71:	learn: 1.0298829	total: 1.77s	remaining: 688ms
72:	learn: 1.0285371	total: 1.79s	remaining: 663ms
73:	learn: 1.0260307	total: 1.82s	remaining: 638ms
74:	learn: 1.0248534	total: 1.84s	remaining: 613ms
75:	learn: 1.0236806	total: 1.86s	remaining: 587ms
76:	learn: 1.0224255	total: 1.88s	remaining: 562ms
77:	learn: 1.0215139	total: 1.9s	remaining: 537ms
78:	learn: 1.0203993	total: 1.92s	remaining: 512ms
79:	learn: 1.0189960	total: 1.95s	remaining: 487ms
80:	learn: 1.0172113	total: 1.98s	remaining: 464ms
81:	learn: 1.0159608	total: 2s	remaining: 439ms
82:	learn: 1.0149338	total: 2.02s	remaining: 414ms
83:	learn: 1.0138187	total: 2.04s	remaining: 390ms
84:	learn: 1.0129400	total: 2.07s	remaining: 365ms
85:	learn: 1.0116632	total: 2.09s	remaining: 340ms
86:	learn: 1.0106550	total: 2.11s	remaining: 316ms
87:	learn: 1.0089417	total: 2.13s	remaining: 291ms
88:	learn: 1.0077766	total: 2.16s	remaining: 267ms
89:	learn: 1.0065799	total: 2.18s	remaining: 242ms
90:	learn: 1.0052572	total: 2.21s	remaining: 218ms
91:	learn: 1.0042263	total: 2.23s	remaining: 194ms
92:	learn: 1.0032914	total: 2.26s	remaining: 170ms
93:	learn: 1.0022445	total: 2.28s	remaining: 146ms
94:	learn: 1.0013918	total: 2.3s	remaining: 121ms
95:	learn: 1.0004444	total: 2.33s	remaining: 96.9ms
96:	learn: 0.9993907	total: 2.35s	remaining: 72.7ms
97:	learn: 0.9986140	total: 2.37s	remaining: 48.4ms

[I 2025-10-10 20:04:37,676] Trial 16 finished with value: 0.995036857369379 and parameters: {'iterations': 100, 'depth': 3, 'learning_rate': 0.08335175645285334}. Best is trial 10 with value: 0.545086205552607.

98:	learn: 0.9973057	total: 2.4s	remaining: 24.2ms
99:	learn: 0.9961367	total: 2.42s	remaining: 0us
Trial 16: RMSE=0.9950, R2=0.3252
0:	learn: 1.2058413	total: 70.9ms	remaining: 4.11s
1:	learn: 1.1903327	total: 138ms	remaining: 3.92s
2:	learn: 1.1776556	total: 230ms	remaining: 4.3s
3:	learn: 1.1662344	total: 302ms	remaining: 4.15s
4:	learn: 1.1510454	total: 367ms	remaining: 3.96s
5:	learn: 1.1391687	total: 436ms	remaining: 3.85s
6:	learn: 1.1285278	total: 499ms	remaining: 3.71s
7:	learn: 1.1194863	total: 573ms	remaining: 3.65s
8:	learn: 1.1099395	total: 649ms	remaining: 3.6s
9:	learn: 1.1004511	total: 717ms	remaining: 3.51s
10:	learn: 1.0929901	total: 789ms	remaining: 3.44s
11:	learn: 1.0837613	total: 854ms	remaining: 3.35s
12:	learn: 1.0743250	total: 920ms	remaining: 3.25s
13:	learn: 1.0668769	total: 980ms	remaining: 3.15s
14:	learn: 1.0609610	total: 1.05s	remaining: 3.07s
15:	learn: 1.0539193	total: 1.11s	remaining: 2.98s
16:	learn: 1.0474344	total: 1.21s	remaining: 2.99s
17:	learn: 1.0422571	total: 1.33s	remaining: 3.04s
18:	learn: 1.0368726	total: 1.45s	remaining: 3.06s
19:	learn: 1.0316526	total: 1.58s	remaining: 3.09s
20:	learn: 1.0257293	total: 1.71s	remaining: 3.09s
21:	learn: 1.0188115	total: 1.86s	remaining: 3.14s
22:	learn: 1.0138736	total: 2s	remaining: 3.13s
23:	learn: 1.0094195	total: 2.12s	remaining: 3.1s
24:	learn: 1.0050717	total: 2.23s	remaining: 3.04s
25:	learn: 1.0008329	total: 2.35s	remaining: 2.99s
26:	learn: 0.9955711	total: 2.48s	remaining: 2.94s
27:	learn: 0.9911054	total: 2.6s	remaining: 2.88s
28:	learn: 0.9859077	total: 2.73s	remaining: 2.83s
29:	learn: 0.9812316	total: 2.84s	remaining: 2.74s
30:	learn: 0.9766966	total: 2.96s	remaining: 2.67s
31:	learn: 0.9733889	total: 3.06s	remaining: 2.58s
32:	learn: 0.9676670	total: 3.17s	remaining: 2.49s
33:	learn: 0.9637738	total: 3.29s	remaining: 2.42s
34:	learn: 0.9607953	total: 3.41s	remaining: 2.34s
35:	learn: 0.9563618	total: 3.54s	remaining: 2.26s
36:	learn: 0.9528590	total: 3.67s	remaining: 2.18s
37:	learn: 0.9475710	total: 3.8s	remaining: 2.1s
38:	learn: 0.9447293	total: 3.91s	remaining: 2.01s
39:	learn: 0.9401146	total: 4.03s	remaining: 1.92s
40:	learn: 0.9377669	total: 4.16s	remaining: 1.82s
41:	learn: 0.9336078	total: 4.28s	remaining: 1.73s
42:	learn: 0.9295649	total: 4.4s	remaining: 1.64s
43:	learn: 0.9257745	total: 4.54s	remaining: 1.55s
44:	learn: 0.9229302	total: 4.67s	remaining: 1.45s
45:	learn: 0.9198775	total: 4.78s	remaining: 1.35s
46:	learn: 0.9176509	total: 4.89s	remaining: 1.25s
47:	learn: 0.9147135	total: 5.02s	remaining: 1.15s
48:	learn: 0.9111929	total: 5.16s	remaining: 1.05s
49:	learn: 0.9095707	total: 5.27s	remaining: 949ms
50:	learn: 0.9071283	total: 5.34s	remaining: 838ms
51:	learn: 0.9042027	total: 5.42s	remaining: 729ms
52:	learn: 0.9019989	total: 5.48s	remaining: 621ms
53:	learn: 0.9000902	total: 5.54s	remaining: 513ms
54:	learn: 0.8981960	total: 5.61s	remaining: 408ms
55:	learn: 0.8964726	total: 5.69s	remaining: 305ms
56:	learn: 0.8939891	total: 5.75s	remaining: 202ms
57:	learn: 0.8917321	total: 5.81s	remaining: 100ms
58:	learn: 0.8889730	total: 5.87s	remaining: 0us

[I 2025-10-10 20:04:47,688] Trial 17 finished with value: 0.7998288602247571 and parameters: {'iterations': 59, 'depth': 7, 'learning_rate': 0.08996020312568373}. Best is trial 10 with value: 0.545086205552607.

Trial 17: RMSE=0.7998, R2=0.4576
0:	learn: 1.2015946	total: 348ms	remaining: 25.4s
1:	learn: 1.1823444	total: 696ms	remaining: 25.1s
2:	learn: 1.1615801	total: 1.06s	remaining: 25.2s
3:	learn: 1.1445277	total: 1.42s	remaining: 24.9s
4:	learn: 1.1288039	total: 1.77s	remaining: 24.5s
5:	learn: 1.1148406	total: 2.14s	remaining: 24.3s
6:	learn: 1.1023742	total: 2.49s	remaining: 23.8s
7:	learn: 1.0882100	total: 2.84s	remaining: 23.4s
8:	learn: 1.0763043	total: 3.21s	remaining: 23.2s
9:	learn: 1.0650736	total: 3.56s	remaining: 22.8s
10:	learn: 1.0526541	total: 3.9s	remaining: 22.4s
11:	learn: 1.0428716	total: 4.27s	remaining: 22.1s
12:	learn: 1.0346445	total: 4.62s	remaining: 21.7s
13:	learn: 1.0255660	total: 4.97s	remaining: 21.3s
14:	learn: 1.0146692	total: 5.37s	remaining: 21.1s
15:	learn: 1.0070487	total: 5.91s	remaining: 21.4s
16:	learn: 0.9998893	total: 6.62s	remaining: 22.2s
17:	learn: 0.9924626	total: 7.29s	remaining: 22.7s
18:	learn: 0.9851424	total: 7.95s	remaining: 23s
19:	learn: 0.9787648	total: 8.67s	remaining: 23.4s
20:	learn: 0.9726265	total: 9.35s	remaining: 23.6s
21:	learn: 0.9660896	total: 10.1s	remaining: 23.8s
22:	learn: 0.9607912	total: 10.8s	remaining: 23.8s
23:	learn: 0.9532111	total: 11.4s	remaining: 23.8s
24:	learn: 0.9472564	total: 12.1s	remaining: 23.7s
25:	learn: 0.9417807	total: 12.7s	remaining: 23.4s
26:	learn: 0.9373773	total: 13.2s	remaining: 23.1s
27:	learn: 0.9317444	total: 13.7s	remaining: 22.6s
28:	learn: 0.9265974	total: 14.1s	remaining: 21.8s
29:	learn: 0.9210583	total: 14.4s	remaining: 21.2s
30:	learn: 0.9147790	total: 14.8s	remaining: 20.5s
31:	learn: 0.9083498	total: 15.2s	remaining: 19.9s
32:	learn: 0.9039325	total: 15.5s	remaining: 19.3s
33:	learn: 0.8986593	total: 15.9s	remaining: 18.7s
34:	learn: 0.8928022	total: 16.2s	remaining: 18.1s
35:	learn: 0.8887695	total: 16.6s	remaining: 17.5s
36:	learn: 0.8854207	total: 16.9s	remaining: 16.9s
37:	learn: 0.8805542	total: 17.3s	remaining: 16.4s
38:	learn: 0.8765747	total: 17.7s	remaining: 15.9s
39:	learn: 0.8732813	total: 18.1s	remaining: 15.4s
40:	learn: 0.8679869	total: 18.4s	remaining: 14.8s
41:	learn: 0.8653393	total: 18.8s	remaining: 14.3s
42:	learn: 0.8612653	total: 19.1s	remaining: 13.8s
43:	learn: 0.8582580	total: 19.5s	remaining: 13.3s
44:	learn: 0.8555769	total: 19.9s	remaining: 12.8s
45:	learn: 0.8518030	total: 20.2s	remaining: 12.3s
46:	learn: 0.8487801	total: 20.6s	remaining: 11.8s
47:	learn: 0.8448341	total: 20.9s	remaining: 11.3s
48:	learn: 0.8411463	total: 21.3s	remaining: 10.9s
49:	learn: 0.8389333	total: 21.6s	remaining: 10.4s
50:	learn: 0.8360577	total: 22s	remaining: 9.93s
51:	learn: 0.8325791	total: 22.4s	remaining: 9.46s
52:	learn: 0.8293199	total: 22.8s	remaining: 9.04s
53:	learn: 0.8256078	total: 23.4s	remaining: 8.65s
54:	learn: 0.8224553	total: 24s	remaining: 8.29s
55:	learn: 0.8180284	total: 24.6s	remaining: 7.91s
56:	learn: 0.8152110	total: 25.2s	remaining: 7.53s
57:	learn: 0.8117613	total: 25.9s	remaining: 7.13s
58:	learn: 0.8087638	total: 26.4s	remaining: 6.71s
59:	learn: 0.8066125	total: 26.9s	remaining: 6.29s
60:	learn: 0.8027195	total: 27.4s	remaining: 5.84s
61:	learn: 0.7988468	total: 27.7s	remaining: 5.37s
62:	learn: 0.7958265	total: 28.1s	remaining: 4.9s
63:	learn: 0.7924668	total: 28.5s	remaining: 4.45s
64:	learn: 0.7886065	total: 28.8s	remaining: 3.99s
65:	learn: 0.7856266	total: 29.2s	remaining: 3.53s
66:	learn: 0.7835500	total: 29.5s	remaining: 3.08s
67:	learn: 0.7808784	total: 29.9s	remaining: 2.63s
68:	learn: 0.7770637	total: 30.2s	remaining: 2.19s
69:	learn: 0.7743036	total: 30.6s	remaining: 1.75s
70:	learn: 0.7716829	total: 30.9s	remaining: 1.31s
71:	learn: 0.7691445	total: 31.3s	remaining: 869ms
72:	learn: 0.7667321	total: 31.7s	remaining: 434ms

[I 2025-10-10 20:05:23,868] Trial 18 finished with value: 0.5997838462484548 and parameters: {'iterations': 74, 'depth': 10, 'learning_rate': 0.07374018192605694}. Best is trial 10 with value: 0.545086205552607.

73:	learn: 0.7633786	total: 32s	remaining: 0us
Trial 18: RMSE=0.5998, R2=0.5932
0:	learn: 1.2129125	total: 175ms	remaining: 8.4s
1:	learn: 1.2046875	total: 354ms	remaining: 8.32s
2:	learn: 1.1961411	total: 545ms	remaining: 8.36s
3:	learn: 1.1877594	total: 711ms	remaining: 8s
4:	learn: 1.1793877	total: 877ms	remaining: 7.72s
5:	learn: 1.1720519	total: 1.1s	remaining: 7.89s
6:	learn: 1.1653979	total: 1.41s	remaining: 8.47s
7:	learn: 1.1595069	total: 1.72s	remaining: 8.81s
8:	learn: 1.1529561	total: 2.04s	remaining: 9.08s
9:	learn: 1.1472119	total: 2.37s	remaining: 9.26s
10:	learn: 1.1401853	total: 2.68s	remaining: 9.27s
11:	learn: 1.1336479	total: 2.99s	remaining: 9.21s
12:	learn: 1.1265688	total: 3.31s	remaining: 9.15s
13:	learn: 1.1195326	total: 3.64s	remaining: 9.1s
14:	learn: 1.1138636	total: 4s	remaining: 9.07s
15:	learn: 1.1080857	total: 4.33s	remaining: 8.92s
16:	learn: 1.1034074	total: 4.6s	remaining: 8.65s
17:	learn: 1.0978032	total: 4.93s	remaining: 8.5s
18:	learn: 1.0935602	total: 5.23s	remaining: 8.25s
19:	learn: 1.0879729	total: 5.5s	remaining: 7.97s
20:	learn: 1.0831633	total: 5.67s	remaining: 7.56s
21:	learn: 1.0789347	total: 5.84s	remaining: 7.17s
22:	learn: 1.0733355	total: 6.03s	remaining: 6.82s
23:	learn: 1.0692951	total: 6.22s	remaining: 6.48s
24:	learn: 1.0647616	total: 6.42s	remaining: 6.17s
25:	learn: 1.0610320	total: 6.61s	remaining: 5.84s
26:	learn: 1.0577687	total: 6.78s	remaining: 5.52s
27:	learn: 1.0536940	total: 6.94s	remaining: 5.21s
28:	learn: 1.0485445	total: 7.13s	remaining: 4.92s
29:	learn: 1.0448592	total: 7.29s	remaining: 4.61s
30:	learn: 1.0402573	total: 7.45s	remaining: 4.32s
31:	learn: 1.0364590	total: 7.61s	remaining: 4.04s
32:	learn: 1.0334668	total: 7.76s	remaining: 3.76s
33:	learn: 1.0304346	total: 7.92s	remaining: 3.5s
34:	learn: 1.0268975	total: 8.13s	remaining: 3.25s
35:	learn: 1.0236112	total: 8.32s	remaining: 3s
36:	learn: 1.0201026	total: 8.5s	remaining: 2.76s
37:	learn: 1.0168862	total: 8.69s	remaining: 2.51s
38:	learn: 1.0144237	total: 8.88s	remaining: 2.28s
39:	learn: 1.0106944	total: 9.09s	remaining: 2.04s
40:	learn: 1.0067991	total: 9.28s	remaining: 1.81s
41:	learn: 1.0042639	total: 9.47s	remaining: 1.58s
42:	learn: 1.0013706	total: 9.65s	remaining: 1.35s
43:	learn: 0.9987308	total: 9.85s	remaining: 1.12s
44:	learn: 0.9960429	total: 10s	remaining: 892ms
45:	learn: 0.9933759	total: 10.2s	remaining: 668ms
46:	learn: 0.9904335	total: 10.4s	remaining: 443ms
47:	learn: 0.9876542	total: 10.6s	remaining: 220ms
48:	learn: 0.9846105	total: 10.7s	remaining: 0us

[I 2025-10-10 20:05:38,719] Trial 19 finished with value: 0.9743207808456729 and parameters: {'iterations': 49, 'depth': 9, 'learning_rate': 0.036072136968986285}. Best is trial 10 with value: 0.545086205552607.

Trial 19: RMSE=0.9743, R2=0.3392
0:	learn: 1.2075636	total: 50.5ms	remaining: 1.92s
1:	learn: 1.1957859	total: 99.2ms	remaining: 1.83s
2:	learn: 1.1792916	total: 148ms	remaining: 1.77s
3:	learn: 1.1676902	total: 196ms	remaining: 1.71s
4:	learn: 1.1579698	total: 242ms	remaining: 1.65s
5:	learn: 1.1475858	total: 294ms	remaining: 1.61s
6:	learn: 1.1370418	total: 343ms	remaining: 1.57s
7:	learn: 1.1283562	total: 391ms	remaining: 1.51s
8:	learn: 1.1203848	total: 441ms	remaining: 1.47s
9:	learn: 1.1118571	total: 517ms	remaining: 1.5s
10:	learn: 1.1036534	total: 597ms	remaining: 1.52s
11:	learn: 1.0960769	total: 667ms	remaining: 1.5s
12:	learn: 1.0891907	total: 761ms	remaining: 1.52s
13:	learn: 1.0823950	total: 852ms	remaining: 1.52s
14:	learn: 1.0771781	total: 949ms	remaining: 1.52s
15:	learn: 1.0710831	total: 1.03s	remaining: 1.49s
16:	learn: 1.0662231	total: 1.12s	remaining: 1.45s
17:	learn: 1.0606094	total: 1.21s	remaining: 1.41s
18:	learn: 1.0564750	total: 1.28s	remaining: 1.35s
19:	learn: 1.0518444	total: 1.37s	remaining: 1.3s
20:	learn: 1.0475723	total: 1.47s	remaining: 1.26s
21:	learn: 1.0428368	total: 1.58s	remaining: 1.22s
22:	learn: 1.0389860	total: 1.68s	remaining: 1.17s
23:	learn: 1.0346794	total: 1.75s	remaining: 1.09s
24:	learn: 1.0302937	total: 1.84s	remaining: 1.03s
25:	learn: 1.0261213	total: 1.94s	remaining: 972ms
26:	learn: 1.0216381	total: 2.03s	remaining: 902ms
27:	learn: 1.0177857	total: 2.12s	remaining: 832ms
28:	learn: 1.0137159	total: 2.2s	remaining: 758ms
29:	learn: 1.0085899	total: 2.29s	remaining: 686ms
30:	learn: 1.0053211	total: 2.38s	remaining: 614ms
31:	learn: 1.0003665	total: 2.48s	remaining: 543ms
32:	learn: 0.9968787	total: 2.6s	remaining: 472ms
33:	learn: 0.9939105	total: 2.69s	remaining: 396ms
34:	learn: 0.9906571	total: 2.8s	remaining: 320ms
35:	learn: 0.9873824	total: 2.89s	remaining: 241ms
36:	learn: 0.9843178	total: 2.99s	remaining: 161ms

[I 2025-10-10 20:05:46,044] Trial 20 finished with value: 0.957287874001235 and parameters: {'iterations': 39, 'depth': 6, 'learning_rate': 0.09242643944206078}. Best is trial 10 with value: 0.545086205552607.

37:	learn: 0.9798980	total: 3.08s	remaining: 81.1ms
38:	learn: 0.9770833	total: 3.17s	remaining: 0us
Trial 20: RMSE=0.9573, R2=0.3508
0:	learn: 1.1946323	total: 370ms	remaining: 23.3s
1:	learn: 1.1691374	total: 716ms	remaining: 22.2s
2:	learn: 1.1447029	total: 1.08s	remaining: 21.9s
3:	learn: 1.1234779	total: 1.45s	remaining: 21.7s
4:	learn: 1.1065297	total: 1.8s	remaining: 21.2s
5:	learn: 1.0916538	total: 2.15s	remaining: 20.8s
6:	learn: 1.0750817	total: 2.52s	remaining: 20.5s
7:	learn: 1.0590542	total: 2.87s	remaining: 20.1s
8:	learn: 1.0454363	total: 3.22s	remaining: 19.7s
9:	learn: 1.0347890	total: 3.59s	remaining: 19.4s
10:	learn: 1.0219240	total: 3.94s	remaining: 19s
11:	learn: 1.0116381	total: 4.29s	remaining: 18.6s
12:	learn: 1.0009836	total: 4.66s	remaining: 18.3s
13:	learn: 0.9918965	total: 5.01s	remaining: 17.9s
14:	learn: 0.9784308	total: 5.36s	remaining: 17.5s
15:	learn: 0.9704212	total: 5.72s	remaining: 17.2s
16:	learn: 0.9610905	total: 6.08s	remaining: 16.8s
17:	learn: 0.9502188	total: 6.44s	remaining: 16.4s
18:	learn: 0.9413816	total: 6.81s	remaining: 16.1s
19:	learn: 0.9322654	total: 7.2s	remaining: 15.8s
20:	learn: 0.9267203	total: 7.78s	remaining: 15.9s
21:	learn: 0.9173594	total: 8.36s	remaining: 16s
22:	learn: 0.9091124	total: 8.95s	remaining: 15.9s
23:	learn: 0.9005798	total: 9.46s	remaining: 15.8s
24:	learn: 0.8949486	total: 10.1s	remaining: 15.7s
25:	learn: 0.8881525	total: 10.7s	remaining: 15.7s
26:	learn: 0.8832708	total: 11.3s	remaining: 15.5s
27:	learn: 0.8769276	total: 11.8s	remaining: 15.2s
28:	learn: 0.8717035	total: 12.2s	remaining: 14.7s
29:	learn: 0.8666307	total: 12.5s	remaining: 14.2s
30:	learn: 0.8601841	total: 12.9s	remaining: 13.7s
31:	learn: 0.8547092	total: 13.2s	remaining: 13.2s
32:	learn: 0.8499472	total: 13.6s	remaining: 12.8s
33:	learn: 0.8457752	total: 13.9s	remaining: 12.3s
34:	learn: 0.8405552	total: 14.3s	remaining: 11.9s
35:	learn: 0.8357767	total: 14.7s	remaining: 11.4s
36:	learn: 0.8314524	total: 15s	remaining: 11s
37:	learn: 0.8280394	total: 15.4s	remaining: 10.5s
38:	learn: 0.8228960	total: 15.7s	remaining: 10.1s
39:	learn: 0.8176027	total: 16.1s	remaining: 9.65s
40:	learn: 0.8126154	total: 16.5s	remaining: 9.23s
41:	learn: 0.8088838	total: 16.8s	remaining: 8.8s
42:	learn: 0.8048071	total: 17.2s	remaining: 8.39s
43:	learn: 0.8019187	total: 17.5s	remaining: 7.97s
44:	learn: 0.7982772	total: 17.9s	remaining: 7.55s
45:	learn: 0.7942077	total: 18.3s	remaining: 7.14s
46:	learn: 0.7908114	total: 18.6s	remaining: 6.73s
47:	learn: 0.7869846	total: 19s	remaining: 6.32s
48:	learn: 0.7824816	total: 19.4s	remaining: 5.92s
49:	learn: 0.7786714	total: 19.7s	remaining: 5.52s
50:	learn: 0.7745484	total: 20.1s	remaining: 5.11s
51:	learn: 0.7697037	total: 20.4s	remaining: 4.71s
52:	learn: 0.7668998	total: 20.8s	remaining: 4.31s
53:	learn: 0.7630043	total: 21.1s	remaining: 3.92s
54:	learn: 0.7579254	total: 21.5s	remaining: 3.52s
55:	learn: 0.7551033	total: 22s	remaining: 3.14s
56:	learn: 0.7524589	total: 22.6s	remaining: 2.77s
57:	learn: 0.7492477	total: 23.2s	remaining: 2.4s
58:	learn: 0.7463452	total: 23.7s	remaining: 2.01s
59:	learn: 0.7433257	total: 24.3s	remaining: 1.62s
60:	learn: 0.7396257	total: 24.9s	remaining: 1.23s
61:	learn: 0.7353760	total: 25.5s	remaining: 823ms
62:	learn: 0.7318704	total: 26.1s	remaining: 414ms

[I 2025-10-10 20:06:17,261] Trial 21 finished with value: 0.5509034526285526 and parameters: {'iterations': 64, 'depth': 10, 'learning_rate': 0.09986372497493935}. Best is trial 10 with value: 0.545086205552607.

63:	learn: 0.7287344	total: 26.5s	remaining: 0us
Trial 21: RMSE=0.5509, R2=0.6264
0:	learn: 1.1947986	total: 349ms	remaining: 21s
1:	learn: 1.1694441	total: 720ms	remaining: 21.2s
2:	learn: 1.1451314	total: 1.07s	remaining: 20.7s
3:	learn: 1.1239916	total: 1.42s	remaining: 20.2s
4:	learn: 1.1071085	total: 1.79s	remaining: 20s
5:	learn: 1.0922930	total: 2.15s	remaining: 19.7s
6:	learn: 1.0752458	total: 2.5s	remaining: 19.3s
7:	learn: 1.0600000	total: 2.9s	remaining: 19.2s
8:	learn: 1.0438677	total: 3.5s	remaining: 20.2s
9:	learn: 1.0322627	total: 3.86s	remaining: 19.7s
10:	learn: 1.0194453	total: 4.21s	remaining: 19.1s
11:	learn: 1.0090222	total: 4.57s	remaining: 18.6s
12:	learn: 0.9962048	total: 4.94s	remaining: 18.2s
13:	learn: 0.9855051	total: 5.28s	remaining: 17.7s
14:	learn: 0.9746735	total: 5.66s	remaining: 17.4s
15:	learn: 0.9670520	total: 6.2s	remaining: 17.4s
16:	learn: 0.9589135	total: 6.79s	remaining: 17.6s
17:	learn: 0.9488331	total: 7.4s	remaining: 17.7s
18:	learn: 0.9424137	total: 7.99s	remaining: 17.7s
19:	learn: 0.9353787	total: 8.59s	remaining: 17.6s
20:	learn: 0.9291245	total: 9.2s	remaining: 17.5s
21:	learn: 0.9217634	total: 9.79s	remaining: 17.4s
22:	learn: 0.9154571	total: 10.3s	remaining: 17s
23:	learn: 0.9057591	total: 10.7s	remaining: 16.4s
24:	learn: 0.8988127	total: 11s	remaining: 15.8s
25:	learn: 0.8941675	total: 11.4s	remaining: 15.3s
26:	learn: 0.8898966	total: 11.7s	remaining: 14.8s
27:	learn: 0.8830263	total: 12.1s	remaining: 14.2s
28:	learn: 0.8777566	total: 12.4s	remaining: 13.7s
29:	learn: 0.8724485	total: 12.8s	remaining: 13.2s
30:	learn: 0.8672938	total: 13.1s	remaining: 12.7s
31:	learn: 0.8615382	total: 13.5s	remaining: 12.2s
32:	learn: 0.8568710	total: 13.9s	remaining: 11.8s
33:	learn: 0.8505391	total: 14.2s	remaining: 11.3s
34:	learn: 0.8431066	total: 14.6s	remaining: 10.8s
35:	learn: 0.8389650	total: 14.9s	remaining: 10.4s
36:	learn: 0.8349653	total: 15.3s	remaining: 9.91s
37:	learn: 0.8281420	total: 15.6s	remaining: 9.47s
38:	learn: 0.8252862	total: 16s	remaining: 9.03s
39:	learn: 0.8182265	total: 16.4s	remaining: 8.59s
40:	learn: 0.8148847	total: 16.7s	remaining: 8.16s
41:	learn: 0.8109456	total: 17.1s	remaining: 7.72s
42:	learn: 0.8069662	total: 17.4s	remaining: 7.29s
43:	learn: 0.8038690	total: 17.8s	remaining: 6.88s
44:	learn: 0.7988965	total: 18.1s	remaining: 6.45s
45:	learn: 0.7943526	total: 18.5s	remaining: 6.03s
46:	learn: 0.7909842	total: 18.9s	remaining: 5.63s
47:	learn: 0.7881488	total: 19.3s	remaining: 5.21s
48:	learn: 0.7843879	total: 19.6s	remaining: 4.8s
49:	learn: 0.7794283	total: 20s	remaining: 4.39s
50:	learn: 0.7753182	total: 20.4s	remaining: 4.01s
51:	learn: 0.7718478	total: 21.1s	remaining: 3.65s
52:	learn: 0.7681202	total: 21.7s	remaining: 3.27s
53:	learn: 0.7639937	total: 22.2s	remaining: 2.88s
54:	learn: 0.7597840	total: 22.9s	remaining: 2.49s
55:	learn: 0.7574250	total: 23.5s	remaining: 2.09s
56:	learn: 0.7527400	total: 24s	remaining: 1.68s
57:	learn: 0.7492934	total: 24.6s	remaining: 1.27s
58:	learn: 0.7467098	total: 25s	remaining: 846ms
59:	learn: 0.7435943	total: 25.3s	remaining: 422ms

[I 2025-10-10 20:06:47,108] Trial 22 finished with value: 0.5679956243631078 and parameters: {'iterations': 61, 'depth': 10, 'learning_rate': 0.0992328486259747}. Best is trial 10 with value: 0.545086205552607.

60:	learn: 0.7416474	total: 25.7s	remaining: 0us
Trial 22: RMSE=0.5680, R2=0.6148
0:	learn: 1.2031128	total: 179ms	remaining: 14.3s
1:	learn: 1.1859572	total: 355ms	remaining: 14s
2:	learn: 1.1682772	total: 520ms	remaining: 13.5s
3:	learn: 1.1514744	total: 701ms	remaining: 13.5s
4:	learn: 1.1392044	total: 886ms	remaining: 13.5s
5:	learn: 1.1243487	total: 1.05s	remaining: 13.1s
6:	learn: 1.1114286	total: 1.21s	remaining: 12.8s
7:	learn: 1.1017777	total: 1.37s	remaining: 12.5s
8:	learn: 1.0895817	total: 1.53s	remaining: 12.2s
9:	learn: 1.0804898	total: 1.68s	remaining: 12s
10:	learn: 1.0707211	total: 1.85s	remaining: 11.8s
11:	learn: 1.0613260	total: 2.03s	remaining: 11.7s
12:	learn: 1.0522783	total: 2.19s	remaining: 11.4s
13:	learn: 1.0437390	total: 2.34s	remaining: 11.2s
14:	learn: 1.0362986	total: 2.5s	remaining: 11s
15:	learn: 1.0286445	total: 2.65s	remaining: 10.8s
16:	learn: 1.0224441	total: 2.82s	remaining: 10.6s
17:	learn: 1.0142972	total: 2.99s	remaining: 10.5s
18:	learn: 1.0084290	total: 3.17s	remaining: 10.3s
19:	learn: 1.0028631	total: 3.32s	remaining: 10.1s
20:	learn: 0.9981956	total: 3.47s	remaining: 9.91s
21:	learn: 0.9912938	total: 3.62s	remaining: 9.72s
22:	learn: 0.9842575	total: 3.78s	remaining: 9.54s
23:	learn: 0.9787847	total: 3.94s	remaining: 9.36s
24:	learn: 0.9736513	total: 4.12s	remaining: 9.23s
25:	learn: 0.9678778	total: 4.28s	remaining: 9.06s
26:	learn: 0.9630632	total: 4.47s	remaining: 8.94s
27:	learn: 0.9568326	total: 4.67s	remaining: 8.83s
28:	learn: 0.9514345	total: 4.86s	remaining: 8.71s
29:	learn: 0.9472088	total: 5.12s	remaining: 8.71s
30:	learn: 0.9432902	total: 5.41s	remaining: 8.72s
31:	learn: 0.9386809	total: 5.73s	remaining: 8.77s
32:	learn: 0.9340839	total: 6.05s	remaining: 8.79s
33:	learn: 0.9299169	total: 6.38s	remaining: 8.81s
34:	learn: 0.9260265	total: 6.63s	remaining: 8.72s
35:	learn: 0.9215517	total: 6.93s	remaining: 8.67s
36:	learn: 0.9176108	total: 7.26s	remaining: 8.64s
37:	learn: 0.9112185	total: 7.6s	remaining: 8.6s
38:	learn: 0.9073225	total: 7.92s	remaining: 8.53s
39:	learn: 0.9033969	total: 8.21s	remaining: 8.41s
40:	learn: 0.8999961	total: 8.54s	remaining: 8.33s
41:	learn: 0.8966868	total: 8.84s	remaining: 8.21s
42:	learn: 0.8926990	total: 9.17s	remaining: 8.11s
43:	learn: 0.8889538	total: 9.37s	remaining: 7.88s
44:	learn: 0.8850489	total: 9.57s	remaining: 7.66s
45:	learn: 0.8818784	total: 9.76s	remaining: 7.42s
46:	learn: 0.8786728	total: 9.96s	remaining: 7.2s
47:	learn: 0.8758672	total: 10.1s	remaining: 6.97s
48:	learn: 0.8731667	total: 10.3s	remaining: 6.74s
49:	learn: 0.8701179	total: 10.5s	remaining: 6.52s
50:	learn: 0.8670431	total: 10.7s	remaining: 6.3s
51:	learn: 0.8648319	total: 10.9s	remaining: 6.06s
52:	learn: 0.8616114	total: 11s	remaining: 5.83s
53:	learn: 0.8591477	total: 11.2s	remaining: 5.6s
54:	learn: 0.8561733	total: 11.4s	remaining: 5.39s
55:	learn: 0.8529846	total: 11.6s	remaining: 5.19s
56:	learn: 0.8482462	total: 11.8s	remaining: 4.97s
57:	learn: 0.8453859	total: 12s	remaining: 4.76s
58:	learn: 0.8427528	total: 12.2s	remaining: 4.55s
59:	learn: 0.8394693	total: 12.4s	remaining: 4.33s
60:	learn: 0.8367879	total: 12.6s	remaining: 4.12s
61:	learn: 0.8346992	total: 12.8s	remaining: 3.91s
62:	learn: 0.8318089	total: 12.9s	remaining: 3.7s
63:	learn: 0.8293521	total: 13.1s	remaining: 3.49s
64:	learn: 0.8274107	total: 13.3s	remaining: 3.27s
65:	learn: 0.8249411	total: 13.5s	remaining: 3.06s
66:	learn: 0.8227401	total: 13.7s	remaining: 2.86s
67:	learn: 0.8189414	total: 13.9s	remaining: 2.65s
68:	learn: 0.8167744	total: 14s	remaining: 2.44s
69:	learn: 0.8150416	total: 14.2s	remaining: 2.23s
70:	learn: 0.8131697	total: 14.4s	remaining: 2.02s
71:	learn: 0.8094060	total: 14.5s	remaining: 1.82s
72:	learn: 0.8072194	total: 14.7s	remaining: 1.61s
73:	learn: 0.8044611	total: 14.9s	remaining: 1.41s
74:	learn: 0.8026339	total: 15.1s	remaining: 1.21s
75:	learn: 0.7999022	total: 15.3s	remaining: 1s
76:	learn: 0.7978550	total: 15.4s	remaining: 802ms
77:	learn: 0.7956415	total: 15.6s	remaining: 600ms
78:	learn: 0.7919111	total: 15.8s	remaining: 399ms
79:	learn: 0.7900107	total: 16s	remaining: 200ms
80:	learn: 0.7880375	total: 16.2s	remaining: 0us

[I 2025-10-10 20:07:07,416] Trial 23 finished with value: 0.6348366916036466 and parameters: {'iterations': 81, 'depth': 9, 'learning_rate': 0.0759655436688407}. Best is trial 10 with value: 0.545086205552607.

Trial 23: RMSE=0.6348, R2=0.5695
0:	learn: 1.2035146	total: 180ms	remaining: 12.4s
1:	learn: 1.1844099	total: 372ms	remaining: 12.6s
2:	learn: 1.1679188	total: 562ms	remaining: 12.5s
3:	learn: 1.1516975	total: 752ms	remaining: 12.4s
4:	learn: 1.1382953	total: 951ms	remaining: 12.4s
5:	learn: 1.1229111	total: 1.15s	remaining: 12.2s
6:	learn: 1.1106153	total: 1.38s	remaining: 12.4s
7:	learn: 1.0998442	total: 1.58s	remaining: 12.3s
8:	learn: 1.0896682	total: 1.78s	remaining: 12s
9:	learn: 1.0810331	total: 1.96s	remaining: 11.7s
10:	learn: 1.0701614	total: 2.13s	remaining: 11.4s
11:	learn: 1.0609285	total: 2.32s	remaining: 11.2s
12:	learn: 1.0521558	total: 2.53s	remaining: 11.1s
13:	learn: 1.0428778	total: 2.72s	remaining: 10.9s
14:	learn: 1.0359112	total: 2.9s	remaining: 10.7s
15:	learn: 1.0286481	total: 3s	remaining: 10.1s
16:	learn: 1.0222972	total: 3.12s	remaining: 9.71s
17:	learn: 1.0157054	total: 3.23s	remaining: 9.32s
18:	learn: 1.0094204	total: 3.33s	remaining: 8.94s
19:	learn: 1.0040746	total: 3.44s	remaining: 8.6s
20:	learn: 0.9977804	total: 3.56s	remaining: 8.3s
21:	learn: 0.9900865	total: 3.66s	remaining: 7.99s
22:	learn: 0.9859259	total: 3.77s	remaining: 7.7s
23:	learn: 0.9793745	total: 3.87s	remaining: 7.43s
24:	learn: 0.9739810	total: 3.98s	remaining: 7.16s
25:	learn: 0.9684951	total: 4.09s	remaining: 6.92s
26:	learn: 0.9635022	total: 4.19s	remaining: 6.67s
27:	learn: 0.9591500	total: 4.29s	remaining: 6.44s
28:	learn: 0.9546031	total: 4.39s	remaining: 6.21s
29:	learn: 0.9503350	total: 4.51s	remaining: 6.01s
30:	learn: 0.9459335	total: 4.61s	remaining: 5.8s
31:	learn: 0.9424995	total: 4.7s	remaining: 5.59s
32:	learn: 0.9381147	total: 4.8s	remaining: 5.38s
33:	learn: 0.9322720	total: 4.91s	remaining: 5.2s
34:	learn: 0.9279772	total: 5s	remaining: 5s
35:	learn: 0.9250860	total: 5.11s	remaining: 4.83s
36:	learn: 0.9215567	total: 5.21s	remaining: 4.64s
37:	learn: 0.9178870	total: 5.31s	remaining: 4.47s
38:	learn: 0.9142559	total: 5.41s	remaining: 4.3s
39:	learn: 0.9118530	total: 5.5s	remaining: 4.12s
40:	learn: 0.9086183	total: 5.62s	remaining: 3.97s
41:	learn: 0.9045225	total: 5.71s	remaining: 3.81s
42:	learn: 0.9000985	total: 5.8s	remaining: 3.64s
43:	learn: 0.8957569	total: 5.91s	remaining: 3.49s
44:	learn: 0.8922007	total: 6.01s	remaining: 3.34s
45:	learn: 0.8888936	total: 6.12s	remaining: 3.19s
46:	learn: 0.8849428	total: 6.2s	remaining: 3.04s
47:	learn: 0.8818095	total: 6.3s	remaining: 2.89s
48:	learn: 0.8791940	total: 6.39s	remaining: 2.74s
49:	learn: 0.8754649	total: 6.48s	remaining: 2.59s
50:	learn: 0.8708398	total: 6.6s	remaining: 2.46s
51:	learn: 0.8683367	total: 6.71s	remaining: 2.32s
52:	learn: 0.8647693	total: 6.81s	remaining: 2.18s
53:	learn: 0.8615227	total: 6.91s	remaining: 2.05s
54:	learn: 0.8590860	total: 7s	remaining: 1.91s
55:	learn: 0.8561676	total: 7.11s	remaining: 1.78s
56:	learn: 0.8534984	total: 7.2s	remaining: 1.64s
57:	learn: 0.8492187	total: 7.32s	remaining: 1.51s
58:	learn: 0.8458384	total: 7.43s	remaining: 1.38s
59:	learn: 0.8426306	total: 7.53s	remaining: 1.25s
60:	learn: 0.8408338	total: 7.62s	remaining: 1.12s
61:	learn: 0.8380525	total: 7.73s	remaining: 998ms
62:	learn: 0.8351762	total: 7.83s	remaining: 871ms
63:	learn: 0.8329459	total: 7.93s	remaining: 744ms
64:	learn: 0.8308051	total: 8.04s	remaining: 618ms
65:	learn: 0.8285300	total: 8.15s	remaining: 494ms
66:	learn: 0.8242000	total: 8.26s	remaining: 370ms
67:	learn: 0.8215276	total: 8.35s	remaining: 246ms
68:	learn: 0.8186260	total: 8.45s	remaining: 122ms

[I 2025-10-10 20:07:20,715] Trial 24 finished with value: 0.6793252481799386 and parameters: {'iterations': 70, 'depth': 8, 'learning_rate': 0.0906868027974939}. Best is trial 10 with value: 0.545086205552607.

69:	learn: 0.8161758	total: 8.54s	remaining: 0us
Trial 24: RMSE=0.6793, R2=0.5393
0:	learn: 1.1965403	total: 425ms	remaining: 22.9s
1:	learn: 1.1729637	total: 933ms	remaining: 24.7s
2:	learn: 1.1499681	total: 1.58s	remaining: 27.4s
3:	learn: 1.1296492	total: 2.17s	remaining: 27.7s
4:	learn: 1.1137817	total: 2.81s	remaining: 28.2s
5:	learn: 1.0996991	total: 3.46s	remaining: 28.2s
6:	learn: 1.0836447	total: 4.03s	remaining: 27.6s
7:	learn: 1.0671588	total: 4.6s	remaining: 27s
8:	learn: 1.0547470	total: 5.08s	remaining: 26s
9:	learn: 1.0435094	total: 5.43s	remaining: 24.4s
10:	learn: 1.0313644	total: 5.79s	remaining: 23.1s
11:	learn: 1.0194014	total: 6.16s	remaining: 22.1s
12:	learn: 1.0092262	total: 6.51s	remaining: 21s
13:	learn: 1.0006399	total: 6.87s	remaining: 20.1s
14:	learn: 0.9914318	total: 7.24s	remaining: 19.3s
15:	learn: 0.9837889	total: 7.59s	remaining: 18.5s
16:	learn: 0.9731021	total: 7.96s	remaining: 17.8s
17:	learn: 0.9651442	total: 8.32s	remaining: 17.1s
18:	learn: 0.9583574	total: 8.67s	remaining: 16.4s
19:	learn: 0.9513942	total: 9.05s	remaining: 15.8s
20:	learn: 0.9457204	total: 9.4s	remaining: 15.2s
21:	learn: 0.9385224	total: 9.75s	remaining: 14.6s
22:	learn: 0.9301048	total: 10.1s	remaining: 14.1s
23:	learn: 0.9233767	total: 10.5s	remaining: 13.5s
24:	learn: 0.9170554	total: 10.8s	remaining: 13s
25:	learn: 0.9121597	total: 11.2s	remaining: 12.5s
26:	learn: 0.9068606	total: 11.5s	remaining: 12s
27:	learn: 0.9012507	total: 11.9s	remaining: 11.5s
28:	learn: 0.8945063	total: 12.2s	remaining: 11s
29:	learn: 0.8867835	total: 12.6s	remaining: 10.5s
30:	learn: 0.8828991	total: 13s	remaining: 10s
31:	learn: 0.8786884	total: 13.3s	remaining: 9.58s
32:	learn: 0.8737739	total: 13.7s	remaining: 9.12s
33:	learn: 0.8677890	total: 14s	remaining: 8.67s
34:	learn: 0.8613174	total: 14.4s	remaining: 8.23s
35:	learn: 0.8567340	total: 14.8s	remaining: 7.79s
36:	learn: 0.8524288	total: 15.2s	remaining: 7.37s
37:	learn: 0.8489444	total: 15.8s	remaining: 7.07s
38:	learn: 0.8443892	total: 16.4s	remaining: 6.74s
39:	learn: 0.8407028	total: 17s	remaining: 6.37s
40:	learn: 0.8345060	total: 17.6s	remaining: 6.01s
41:	learn: 0.8303135	total: 18.2s	remaining: 5.64s
42:	learn: 0.8272508	total: 18.8s	remaining: 5.24s
43:	learn: 0.8236832	total: 19.4s	remaining: 4.84s
44:	learn: 0.8192903	total: 19.8s	remaining: 4.41s
45:	learn: 0.8149572	total: 20.2s	remaining: 3.95s
46:	learn: 0.8112906	total: 20.5s	remaining: 3.5s
47:	learn: 0.8087365	total: 20.9s	remaining: 3.05s
48:	learn: 0.8049940	total: 21.3s	remaining: 2.6s
49:	learn: 0.8011742	total: 21.6s	remaining: 2.16s
50:	learn: 0.7982703	total: 22s	remaining: 1.72s
51:	learn: 0.7935892	total: 22.3s	remaining: 1.29s
52:	learn: 0.7910248	total: 22.7s	remaining: 856ms
53:	learn: 0.7856115	total: 23s	remaining: 427ms

[I 2025-10-10 20:07:48,261] Trial 25 finished with value: 0.6295518491033428 and parameters: {'iterations': 55, 'depth': 10, 'learning_rate': 0.09264761327521778}. Best is trial 10 with value: 0.545086205552607.

54:	learn: 0.7818527	total: 23.4s	remaining: 0us
Trial 25: RMSE=0.6296, R2=0.5731
0:	learn: 1.2044457	total: 175ms	remaining: 13.5s
1:	learn: 1.1884252	total: 352ms	remaining: 13.4s
2:	learn: 1.1718256	total: 518ms	remaining: 13s
3:	learn: 1.1559444	total: 704ms	remaining: 13s
4:	learn: 1.1443483	total: 896ms	remaining: 13.1s
5:	learn: 1.1334173	total: 1.05s	remaining: 12.6s
6:	learn: 1.1212252	total: 1.22s	remaining: 12.3s
7:	learn: 1.1073935	total: 1.38s	remaining: 12.1s
8:	learn: 1.0968885	total: 1.55s	remaining: 11.9s
9:	learn: 1.0877296	total: 1.72s	remaining: 11.7s
10:	learn: 1.0799891	total: 1.94s	remaining: 11.8s
11:	learn: 1.0713710	total: 2.13s	remaining: 11.7s
12:	learn: 1.0624194	total: 2.41s	remaining: 12s
13:	learn: 1.0553484	total: 2.72s	remaining: 12.4s
14:	learn: 1.0473178	total: 3.08s	remaining: 12.9s
15:	learn: 1.0404903	total: 3.38s	remaining: 13.1s
16:	learn: 1.0329434	total: 3.68s	remaining: 13.2s
17:	learn: 1.0252819	total: 4.02s	remaining: 13.4s
18:	learn: 1.0184090	total: 4.36s	remaining: 13.5s
19:	learn: 1.0129698	total: 4.69s	remaining: 13.6s
20:	learn: 1.0079945	total: 5.01s	remaining: 13.6s
21:	learn: 1.0023988	total: 5.33s	remaining: 13.6s
22:	learn: 0.9954791	total: 5.63s	remaining: 13.5s
23:	learn: 0.9897818	total: 5.97s	remaining: 13.4s
24:	learn: 0.9845839	total: 6.28s	remaining: 13.3s
25:	learn: 0.9797606	total: 6.55s	remaining: 13.1s
26:	learn: 0.9754276	total: 6.72s	remaining: 12.7s
27:	learn: 0.9704439	total: 6.89s	remaining: 12.3s
28:	learn: 0.9666542	total: 7.07s	remaining: 11.9s
29:	learn: 0.9609211	total: 7.3s	remaining: 11.7s
30:	learn: 0.9563785	total: 7.47s	remaining: 11.3s
31:	learn: 0.9519071	total: 7.65s	remaining: 11s
32:	learn: 0.9483092	total: 7.81s	remaining: 10.7s
33:	learn: 0.9427914	total: 7.98s	remaining: 10.3s
34:	learn: 0.9384143	total: 8.14s	remaining: 10s
35:	learn: 0.9346261	total: 8.35s	remaining: 9.74s
36:	learn: 0.9292932	total: 8.54s	remaining: 9.46s
37:	learn: 0.9251887	total: 8.73s	remaining: 9.2s
38:	learn: 0.9221814	total: 8.91s	remaining: 8.91s
39:	learn: 0.9177608	total: 9.09s	remaining: 8.63s
40:	learn: 0.9148975	total: 9.27s	remaining: 8.37s
41:	learn: 0.9092668	total: 9.5s	remaining: 8.14s
42:	learn: 0.9051696	total: 9.68s	remaining: 7.88s
43:	learn: 0.9013213	total: 9.86s	remaining: 7.62s
44:	learn: 0.8977908	total: 10s	remaining: 7.35s
45:	learn: 0.8947329	total: 10.2s	remaining: 7.09s
46:	learn: 0.8909786	total: 10.4s	remaining: 6.83s
47:	learn: 0.8877056	total: 10.6s	remaining: 6.61s
48:	learn: 0.8848949	total: 10.8s	remaining: 6.37s
49:	learn: 0.8817841	total: 10.9s	remaining: 6.13s
50:	learn: 0.8786522	total: 11.1s	remaining: 5.88s
51:	learn: 0.8748418	total: 11.3s	remaining: 5.64s
52:	learn: 0.8723169	total: 11.4s	remaining: 5.4s
53:	learn: 0.8694002	total: 11.6s	remaining: 5.17s
54:	learn: 0.8666571	total: 11.8s	remaining: 4.94s
55:	learn: 0.8623844	total: 12s	remaining: 4.72s
56:	learn: 0.8588784	total: 12.2s	remaining: 4.49s
57:	learn: 0.8563504	total: 12.4s	remaining: 4.26s
58:	learn: 0.8525825	total: 12.6s	remaining: 4.05s
59:	learn: 0.8496295	total: 12.8s	remaining: 3.83s
60:	learn: 0.8472837	total: 12.9s	remaining: 3.6s
61:	learn: 0.8452602	total: 13.1s	remaining: 3.38s
62:	learn: 0.8424120	total: 13.3s	remaining: 3.16s
63:	learn: 0.8390626	total: 13.5s	remaining: 2.95s
64:	learn: 0.8368510	total: 13.7s	remaining: 2.73s
65:	learn: 0.8343046	total: 13.8s	remaining: 2.52s
66:	learn: 0.8314217	total: 14s	remaining: 2.3s
67:	learn: 0.8281385	total: 14.2s	remaining: 2.08s
68:	learn: 0.8260148	total: 14.3s	remaining: 1.87s
69:	learn: 0.8238627	total: 14.5s	remaining: 1.66s
70:	learn: 0.8217704	total: 14.7s	remaining: 1.45s
71:	learn: 0.8193071	total: 14.8s	remaining: 1.24s
72:	learn: 0.8155139	total: 15s	remaining: 1.03s
73:	learn: 0.8116230	total: 15.2s	remaining: 820ms
74:	learn: 0.8098280	total: 15.3s	remaining: 613ms
75:	learn: 0.8073127	total: 15.5s	remaining: 408ms
76:	learn: 0.8044518	total: 15.6s	remaining: 203ms

[I 2025-10-10 20:08:08,224] Trial 26 finished with value: 0.6543668580402345 and parameters: {'iterations': 78, 'depth': 9, 'learning_rate': 0.07046008394997433}. Best is trial 10 with value: 0.545086205552607.

77:	learn: 0.8004092	total: 15.8s	remaining: 0us
Trial 26: RMSE=0.6544, R2=0.5562
0:	learn: 1.1988657	total: 363ms	remaining: 23.2s
1:	learn: 1.1772581	total: 713ms	remaining: 22.5s
2:	learn: 1.1560407	total: 1.07s	remaining: 22.1s
3:	learn: 1.1370539	total: 1.44s	remaining: 22s
4:	learn: 1.1207030	total: 1.8s	remaining: 21.6s
5:	learn: 1.1075725	total: 2.15s	remaining: 21.2s
6:	learn: 1.0951634	total: 2.52s	remaining: 20.9s
7:	learn: 1.0803982	total: 2.88s	remaining: 20.5s
8:	learn: 1.0641789	total: 3.23s	remaining: 20.1s
9:	learn: 1.0541910	total: 3.6s	remaining: 19.8s
10:	learn: 1.0424996	total: 3.96s	remaining: 19.5s
11:	learn: 1.0315465	total: 4.32s	remaining: 19.1s
12:	learn: 1.0212156	total: 4.69s	remaining: 18.8s
13:	learn: 1.0103429	total: 5.04s	remaining: 18.4s
14:	learn: 0.9997510	total: 5.4s	remaining: 18s
15:	learn: 0.9916125	total: 5.77s	remaining: 17.7s
16:	learn: 0.9813972	total: 6.13s	remaining: 17.3s
17:	learn: 0.9736585	total: 6.48s	remaining: 16.9s
18:	learn: 0.9669239	total: 6.86s	remaining: 16.6s
19:	learn: 0.9587826	total: 7.2s	remaining: 16.2s
20:	learn: 0.9536035	total: 7.55s	remaining: 15.8s
21:	learn: 0.9480581	total: 7.92s	remaining: 15.5s
22:	learn: 0.9412351	total: 8.28s	remaining: 15.1s
23:	learn: 0.9339977	total: 8.63s	remaining: 14.7s
24:	learn: 0.9281766	total: 9s	remaining: 14.4s
25:	learn: 0.9214951	total: 9.35s	remaining: 14s
26:	learn: 0.9163300	total: 9.73s	remaining: 13.7s
27:	learn: 0.9115969	total: 10.3s	remaining: 13.6s
28:	learn: 0.9055622	total: 10.9s	remaining: 13.5s
29:	learn: 0.8987879	total: 11.5s	remaining: 13.4s
30:	learn: 0.8929874	total: 12.1s	remaining: 13.3s
31:	learn: 0.8896191	total: 12.7s	remaining: 13.1s
32:	learn: 0.8849362	total: 13.3s	remaining: 12.9s
33:	learn: 0.8787462	total: 13.9s	remaining: 12.7s
34:	learn: 0.8740456	total: 14.3s	remaining: 12.3s
35:	learn: 0.8704592	total: 14.7s	remaining: 11.8s
36:	learn: 0.8659035	total: 15s	remaining: 11.4s
37:	learn: 0.8610333	total: 15.4s	remaining: 10.9s
38:	learn: 0.8565493	total: 15.8s	remaining: 10.5s
39:	learn: 0.8511729	total: 16.1s	remaining: 10.1s
40:	learn: 0.8466112	total: 16.5s	remaining: 9.64s
41:	learn: 0.8431318	total: 16.8s	remaining: 9.21s
42:	learn: 0.8391950	total: 17.2s	remaining: 8.79s
43:	learn: 0.8353989	total: 17.5s	remaining: 8.37s
44:	learn: 0.8318188	total: 17.9s	remaining: 7.95s
45:	learn: 0.8282501	total: 18.2s	remaining: 7.53s
46:	learn: 0.8242291	total: 18.6s	remaining: 7.12s
47:	learn: 0.8219069	total: 18.9s	remaining: 6.71s
48:	learn: 0.8182184	total: 19.3s	remaining: 6.3s
49:	learn: 0.8150040	total: 19.7s	remaining: 5.9s
50:	learn: 0.8102171	total: 20s	remaining: 5.5s
51:	learn: 0.8052122	total: 20.4s	remaining: 5.09s
52:	learn: 0.8028326	total: 20.7s	remaining: 4.7s
53:	learn: 0.7983254	total: 21.1s	remaining: 4.3s
54:	learn: 0.7928797	total: 21.5s	remaining: 3.9s
55:	learn: 0.7906297	total: 21.8s	remaining: 3.51s
56:	learn: 0.7872040	total: 22.2s	remaining: 3.11s
57:	learn: 0.7840129	total: 22.5s	remaining: 2.72s
58:	learn: 0.7811192	total: 22.9s	remaining: 2.33s
59:	learn: 0.7788868	total: 23.3s	remaining: 1.94s
60:	learn: 0.7740581	total: 23.6s	remaining: 1.55s
61:	learn: 0.7711736	total: 24.1s	remaining: 1.16s
62:	learn: 0.7675593	total: 24.8s	remaining: 786ms
63:	learn: 0.7652203	total: 25.4s	remaining: 397ms

[I 2025-10-10 20:08:40,390] Trial 27 finished with value: 0.6008972409304847 and parameters: {'iterations': 65, 'depth': 10, 'learning_rate': 0.08391172000739139}. Best is trial 10 with value: 0.545086205552607.

64:	learn: 0.7625349	total: 26s	remaining: 0us
Trial 27: RMSE=0.6009, R2=0.5925
0:	learn: 1.2118774	total: 106ms	remaining: 5.85s
1:	learn: 1.2002539	total: 209ms	remaining: 5.63s
2:	learn: 1.1902251	total: 314ms	remaining: 5.54s
3:	learn: 1.1812838	total: 429ms	remaining: 5.58s
4:	learn: 1.1732205	total: 533ms	remaining: 5.44s
5:	learn: 1.1636826	total: 634ms	remaining: 5.29s
6:	learn: 1.1568827	total: 744ms	remaining: 5.21s
7:	learn: 1.1481765	total: 857ms	remaining: 5.14s
8:	learn: 1.1410558	total: 960ms	remaining: 5.01s
9:	learn: 1.1329389	total: 1.09s	remaining: 5.02s
10:	learn: 1.1261483	total: 1.19s	remaining: 4.86s
11:	learn: 1.1203176	total: 1.29s	remaining: 4.73s
12:	learn: 1.1139823	total: 1.39s	remaining: 4.59s
13:	learn: 1.1085993	total: 1.5s	remaining: 4.5s
14:	learn: 1.1028971	total: 1.59s	remaining: 4.36s
15:	learn: 1.0963432	total: 1.71s	remaining: 4.27s
16:	learn: 1.0915599	total: 1.8s	remaining: 4.14s
17:	learn: 1.0856366	total: 1.9s	remaining: 4.02s
18:	learn: 1.0806194	total: 2s	remaining: 3.9s
19:	learn: 1.0753399	total: 2.13s	remaining: 3.84s
20:	learn: 1.0701036	total: 2.23s	remaining: 3.72s
21:	learn: 1.0651047	total: 2.33s	remaining: 3.6s
22:	learn: 1.0609093	total: 2.42s	remaining: 3.47s
23:	learn: 1.0553844	total: 2.52s	remaining: 3.37s
24:	learn: 1.0502341	total: 2.62s	remaining: 3.25s
25:	learn: 1.0455398	total: 2.72s	remaining: 3.14s
26:	learn: 1.0416202	total: 2.82s	remaining: 3.03s
27:	learn: 1.0380111	total: 2.92s	remaining: 2.92s
28:	learn: 1.0335036	total: 3.01s	remaining: 2.81s
29:	learn: 1.0290505	total: 3.14s	remaining: 2.72s
30:	learn: 1.0259837	total: 3.23s	remaining: 2.61s
31:	learn: 1.0217606	total: 3.33s	remaining: 2.5s
32:	learn: 1.0182543	total: 3.44s	remaining: 2.39s
33:	learn: 1.0153599	total: 3.54s	remaining: 2.29s
34:	learn: 1.0114325	total: 3.64s	remaining: 2.18s
35:	learn: 1.0077109	total: 3.75s	remaining: 2.08s
36:	learn: 1.0034183	total: 3.85s	remaining: 1.98s
37:	learn: 1.0001129	total: 3.95s	remaining: 1.87s
38:	learn: 0.9974892	total: 4.05s	remaining: 1.76s
39:	learn: 0.9933024	total: 4.17s	remaining: 1.67s
40:	learn: 0.9906243	total: 4.27s	remaining: 1.56s
41:	learn: 0.9881905	total: 4.38s	remaining: 1.46s
42:	learn: 0.9852961	total: 4.47s	remaining: 1.35s
43:	learn: 0.9824015	total: 4.57s	remaining: 1.25s
44:	learn: 0.9800370	total: 4.67s	remaining: 1.14s
45:	learn: 0.9773360	total: 4.76s	remaining: 1.04s
46:	learn: 0.9735862	total: 4.86s	remaining: 931ms
47:	learn: 0.9708209	total: 4.97s	remaining: 828ms
48:	learn: 0.9675333	total: 5.07s	remaining: 724ms
49:	learn: 0.9651040	total: 5.17s	remaining: 620ms
50:	learn: 0.9629180	total: 5.29s	remaining: 519ms
51:	learn: 0.9604838	total: 5.4s	remaining: 416ms
52:	learn: 0.9582384	total: 5.5s	remaining: 311ms
53:	learn: 0.9558522	total: 5.6s	remaining: 207ms
54:	learn: 0.9532990	total: 5.69s	remaining: 104ms

[I 2025-10-10 20:08:52,970] Trial 28 finished with value: 0.9129036751930916 and parameters: {'iterations': 56, 'depth': 8, 'learning_rate': 0.048889398065649056}. Best is trial 10 with value: 0.545086205552607.

55:	learn: 0.9513357	total: 5.79s	remaining: 0us
Trial 28: RMSE=0.9129, R2=0.3809
0:	learn: 1.2151749	total: 59.5ms	remaining: 5.35s
1:	learn: 1.2090480	total: 106ms	remaining: 4.7s
2:	learn: 1.2035448	total: 137ms	remaining: 4.01s
3:	learn: 1.1960877	total: 174ms	remaining: 3.79s
4:	learn: 1.1910206	total: 240ms	remaining: 4.13s
5:	learn: 1.1847956	total: 301ms	remaining: 4.26s
6:	learn: 1.1802969	total: 353ms	remaining: 4.24s
7:	learn: 1.1761008	total: 405ms	remaining: 4.2s
8:	learn: 1.1716882	total: 448ms	remaining: 4.08s
9:	learn: 1.1671232	total: 495ms	remaining: 4.01s
10:	learn: 1.1625073	total: 548ms	remaining: 3.98s
11:	learn: 1.1587603	total: 596ms	remaining: 3.92s
12:	learn: 1.1553538	total: 640ms	remaining: 3.84s
13:	learn: 1.1517936	total: 671ms	remaining: 3.69s
14:	learn: 1.1482904	total: 709ms	remaining: 3.59s
15:	learn: 1.1447125	total: 772ms	remaining: 3.62s
16:	learn: 1.1413572	total: 823ms	remaining: 3.58s
17:	learn: 1.1381719	total: 860ms	remaining: 3.49s
18:	learn: 1.1346752	total: 895ms	remaining: 3.39s
19:	learn: 1.1318708	total: 940ms	remaining: 3.34s
20:	learn: 1.1289761	total: 972ms	remaining: 3.24s
21:	learn: 1.1261380	total: 1.03s	remaining: 3.22s
22:	learn: 1.1226657	total: 1.08s	remaining: 3.21s
23:	learn: 1.1201906	total: 1.13s	remaining: 3.16s
24:	learn: 1.1176060	total: 1.17s	remaining: 3.1s
25:	learn: 1.1151956	total: 1.22s	remaining: 3.05s
26:	learn: 1.1125264	total: 1.28s	remaining: 3.04s
27:	learn: 1.1103185	total: 1.34s	remaining: 3.02s
28:	learn: 1.1076068	total: 1.39s	remaining: 2.97s
29:	learn: 1.1046892	total: 1.44s	remaining: 2.92s
30:	learn: 1.1025286	total: 1.5s	remaining: 2.9s
31:	learn: 1.1004109	total: 1.54s	remaining: 2.84s
32:	learn: 1.0979960	total: 1.59s	remaining: 2.8s
33:	learn: 1.0962513	total: 1.65s	remaining: 2.77s
34:	learn: 1.0938112	total: 1.72s	remaining: 2.75s
35:	learn: 1.0920531	total: 1.77s	remaining: 2.71s
36:	learn: 1.0900478	total: 1.83s	remaining: 2.67s
37:	learn: 1.0874970	total: 1.87s	remaining: 2.61s
38:	learn: 1.0857182	total: 1.93s	remaining: 2.58s
39:	learn: 1.0838166	total: 1.98s	remaining: 2.52s
40:	learn: 1.0817753	total: 2.04s	remaining: 2.48s
41:	learn: 1.0797934	total: 2.08s	remaining: 2.43s
42:	learn: 1.0778286	total: 2.13s	remaining: 2.38s
43:	learn: 1.0758813	total: 2.18s	remaining: 2.33s
44:	learn: 1.0738865	total: 2.23s	remaining: 2.27s
45:	learn: 1.0719730	total: 2.28s	remaining: 2.23s
46:	learn: 1.0698398	total: 2.35s	remaining: 2.2s
47:	learn: 1.0676724	total: 2.4s	remaining: 2.15s
48:	learn: 1.0659127	total: 2.44s	remaining: 2.09s
49:	learn: 1.0638385	total: 2.49s	remaining: 2.04s
50:	learn: 1.0621341	total: 2.52s	remaining: 1.98s
51:	learn: 1.0604951	total: 2.56s	remaining: 1.92s
52:	learn: 1.0589941	total: 2.62s	remaining: 1.88s
53:	learn: 1.0569034	total: 2.67s	remaining: 1.83s
54:	learn: 1.0552117	total: 2.72s	remaining: 1.78s
55:	learn: 1.0538032	total: 2.76s	remaining: 1.73s
56:	learn: 1.0512376	total: 2.82s	remaining: 1.68s
57:	learn: 1.0497112	total: 2.88s	remaining: 1.64s
58:	learn: 1.0482653	total: 2.92s	remaining: 1.58s
59:	learn: 1.0467775	total: 2.98s	remaining: 1.54s
60:	learn: 1.0451199	total: 3.03s	remaining: 1.49s
61:	learn: 1.0438170	total: 3.08s	remaining: 1.44s
62:	learn: 1.0424880	total: 3.12s	remaining: 1.39s
63:	learn: 1.0408393	total: 3.17s	remaining: 1.34s
64:	learn: 1.0395200	total: 3.22s	remaining: 1.29s
65:	learn: 1.0380919	total: 3.27s	remaining: 1.24s
66:	learn: 1.0367449	total: 3.32s	remaining: 1.19s
67:	learn: 1.0354586	total: 3.35s	remaining: 1.13s
68:	learn: 1.0342702	total: 3.38s	remaining: 1.08s
69:	learn: 1.0331361	total: 3.4s	remaining: 1.02s
70:	learn: 1.0314990	total: 3.43s	remaining: 965ms
71:	learn: 1.0300894	total: 3.46s	remaining: 912ms
72:	learn: 1.0290839	total: 3.49s	remaining: 861ms
73:	learn: 1.0279622	total: 3.52s	remaining: 808ms
74:	learn: 1.0268926	total: 3.54s	remaining: 755ms
75:	learn: 1.0254962	total: 3.56s	remaining: 703ms
76:	learn: 1.0242065	total: 3.59s	remaining: 653ms
77:	learn: 1.0229213	total: 3.61s	remaining: 602ms
78:	learn: 1.0218237	total: 3.64s	remaining: 553ms
79:	learn: 1.0207498	total: 3.66s	remaining: 503ms
80:	learn: 1.0196923	total: 3.68s	remaining: 455ms
81:	learn: 1.0185459	total: 3.7s	remaining: 407ms
82:	learn: 1.0176044	total: 3.73s	remaining: 359ms
83:	learn: 1.0165629	total: 3.75s	remaining: 313ms
84:	learn: 1.0154801	total: 3.78s	remaining: 267ms

[I 2025-10-10 20:09:01,403] Trial 29 finished with value: 1.0185837996142573 and parameters: {'iterations': 91, 'depth': 3, 'learning_rate': 0.08009987677244311}. Best is trial 10 with value: 0.545086205552607.

85:	learn: 1.0141927	total: 3.8s	remaining: 221ms
86:	learn: 1.0133616	total: 3.83s	remaining: 176ms
87:	learn: 1.0120607	total: 3.85s	remaining: 131ms
88:	learn: 1.0106901	total: 3.87s	remaining: 87.1ms
89:	learn: 1.0092290	total: 3.9s	remaining: 43.3ms
90:	learn: 1.0080561	total: 3.92s	remaining: 0us
Trial 29: RMSE=1.0186, R2=0.3092
Best trial value (RMSE): 0.545086205552607
Best hyperparameters: {'iterations': 68, 'depth': 10, 'learning_rate': 0.09868370473288476}

In [29]:
catboost_model = CatBoostRegressor(
        iterations=study.best_params['iterations'],
        depth=study.best_params['depth'],
        learning_rate=study.best_params['learning_rate'],
        random_state=42
    )
catboost_model.fit(X_train, y_train)

0:	learn: 1.1949435	total: 353ms	remaining: 23.6s
1:	learn: 1.1697113	total: 701ms	remaining: 23.1s
2:	learn: 1.1455050	total: 1.08s	remaining: 23.4s
3:	learn: 1.1244398	total: 1.43s	remaining: 22.8s
4:	learn: 1.1075744	total: 1.78s	remaining: 22.4s
5:	learn: 1.0893700	total: 2.14s	remaining: 22.2s
6:	learn: 1.0747777	total: 2.49s	remaining: 21.7s
7:	learn: 1.0607428	total: 2.84s	remaining: 21.3s
8:	learn: 1.0473669	total: 3.21s	remaining: 21.1s
9:	learn: 1.0354013	total: 3.56s	remaining: 20.7s
10:	learn: 1.0232883	total: 3.92s	remaining: 20.3s
11:	learn: 1.0131023	total: 4.29s	remaining: 20s
12:	learn: 1.0013075	total: 4.63s	remaining: 19.6s
13:	learn: 0.9892312	total: 4.99s	remaining: 19.2s
14:	learn: 0.9792885	total: 5.42s	remaining: 19.1s
15:	learn: 0.9711041	total: 5.95s	remaining: 19.3s
16:	learn: 0.9630615	total: 6.56s	remaining: 19.7s
17:	learn: 0.9556894	total: 7.18s	remaining: 19.9s
18:	learn: 0.9471939	total: 7.79s	remaining: 20.1s
19:	learn: 0.9401439	total: 8.41s	remaining: 20.2s
20:	learn: 0.9341115	total: 9s	remaining: 20.1s
21:	learn: 0.9267369	total: 9.55s	remaining: 20s
22:	learn: 0.9200991	total: 10.1s	remaining: 19.7s
23:	learn: 0.9132039	total: 10.4s	remaining: 19.1s
24:	learn: 0.9053580	total: 10.8s	remaining: 18.6s
25:	learn: 0.9002388	total: 11.1s	remaining: 18s
26:	learn: 0.8956069	total: 11.5s	remaining: 17.5s
27:	learn: 0.8888139	total: 11.9s	remaining: 17s
28:	learn: 0.8832996	total: 12.2s	remaining: 16.4s
29:	learn: 0.8759395	total: 12.6s	remaining: 15.9s
30:	learn: 0.8695598	total: 12.9s	remaining: 15.4s
31:	learn: 0.8662576	total: 13.3s	remaining: 15s
32:	learn: 0.8616391	total: 13.7s	remaining: 14.5s
33:	learn: 0.8555021	total: 14s	remaining: 14s
34:	learn: 0.8504282	total: 14.4s	remaining: 13.5s
35:	learn: 0.8463992	total: 14.7s	remaining: 13.1s
36:	learn: 0.8404627	total: 15.1s	remaining: 12.6s
37:	learn: 0.8366048	total: 15.4s	remaining: 12.2s
38:	learn: 0.8330944	total: 15.8s	remaining: 11.7s
39:	learn: 0.8295134	total: 16.1s	remaining: 11.3s
40:	learn: 0.8238953	total: 16.5s	remaining: 10.9s
41:	learn: 0.8183102	total: 16.9s	remaining: 10.4s
42:	learn: 0.8142263	total: 17.2s	remaining: 10s
43:	learn: 0.8112329	total: 17.6s	remaining: 9.57s
44:	learn: 0.8077322	total: 17.9s	remaining: 9.16s
45:	learn: 0.8037996	total: 18.3s	remaining: 8.74s
46:	learn: 0.7995015	total: 18.6s	remaining: 8.32s
47:	learn: 0.7937396	total: 19s	remaining: 7.91s
48:	learn: 0.7903676	total: 19.3s	remaining: 7.5s
49:	learn: 0.7879078	total: 19.7s	remaining: 7.09s
50:	learn: 0.7856044	total: 20.1s	remaining: 6.71s
51:	learn: 0.7820866	total: 20.7s	remaining: 6.36s
52:	learn: 0.7778998	total: 21.3s	remaining: 6.03s
53:	learn: 0.7733305	total: 21.9s	remaining: 5.67s
54:	learn: 0.7694199	total: 22.5s	remaining: 5.32s
55:	learn: 0.7652892	total: 23.1s	remaining: 4.96s
56:	learn: 0.7621835	total: 23.8s	remaining: 4.59s
57:	learn: 0.7595017	total: 24.3s	remaining: 4.19s
58:	learn: 0.7559401	total: 24.7s	remaining: 3.76s
59:	learn: 0.7527466	total: 25s	remaining: 3.34s
60:	learn: 0.7509243	total: 25.4s	remaining: 2.91s
61:	learn: 0.7476950	total: 25.8s	remaining: 2.49s
62:	learn: 0.7432410	total: 26.1s	remaining: 2.07s
63:	learn: 0.7383509	total: 26.4s	remaining: 1.65s
64:	learn: 0.7349152	total: 26.8s	remaining: 1.24s
65:	learn: 0.7304041	total: 27.2s	remaining: 823ms
66:	learn: 0.7281311	total: 27.5s	remaining: 411ms
67:	learn: 0.7248398	total: 27.9s	remaining: 0us

In [32]:
from joblib import dump, load
from pathlib import Path

model_dir_path = '/content/drive/MyDrive/CatBoost_solubility'

dump(catboost_model, Path(model_dir_path) / 'catboost_for_solubility_pred.joblib')

['/content/drive/MyDrive/CatBoost_solubility/catboost_for_solubility_pred.joblib']