Скачивание необходимых библиотек

In [ ]:
!pip install rdkit -qq

In [ ]:
!pip install optuna -qq

In [ ]:
!pip install xgboost -qq

Импортирование библиотек

In [ ]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from rdkit.Chem import PandasTools
from rdkit import DataStructs
import optuna

Чтение файла и удаление нулевых элементов

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/BigSolDB/BigSolDBv2.0.csv')
df = df.dropna()

Просмотр данных

In [ ]:
df.columns

Index(['SMILES_Solute', 'Temperature_K', 'Solvent', 'SMILES_Solvent',
       'Solubility(mole_fraction)', 'Solubility(mol/L)', 'LogS(mol/L)',
       'Compound_Name', 'CAS', 'PubChem_CID', 'FDA_Approved', 'Source'],
      dtype='object')

In [ ]:
df['Solvent'].unique()

array(['ethanol', 'methanol', 'isopropanol', 'water', 'ethyl acetate',
       'n-propanol', 'acetone', 'n-butanol', 'acetonitrile', 'DMF',
       'toluene', 'isobutanol', '1,4-dioxane', 'methyl acetate', 'THF',
       '2-butanone', 'n-pentanol', 'sec-butanol', 'n-hexane',
       'ethylene glycol', 'NMP', 'cyclohexane', 'DMSO', 'n-butyl acetate',
       'n-octanol', 'chloroform', 'n-propyl acetate', 'acetic acid',
       'dichloromethane', 'cyclohexanone', 'propylene glycol',
       'isopropyl acetate', 'DMAc', '2-ethoxyethanol', 'isopentanol',
       'n-heptane', 'ethyl formate', 'benzene', '1,2-dichloroethane',
       'n-hexanol', '2-methoxyethanol', 'isobutyl acetate',
       'tetrachloromethane', 'n-pentyl acetate', 'transcutol',
       'n-heptanol', 'ethylbenzene', 'MIBK', '2-propoxyethanol',
       'tert-butanol', 'MTBE', '2-butoxyethanol', 'propionic acid',
       'o-xylene', 'formic acid', 'diethyl ether', 'm-xylene', 'p-xylene',
       'chlorobenzene', 'dimethyl carbonate', 'n-octane', 'formamide',
       'cyclopentanone', 'anisole', 'gamma-butyrolactone', 'n-dodecane',
       'n-nonanol', 'n-pentane', 'n-butyric acid', 'n-decanol'],
      dtype=object)

Создание копии исходного датасета для обработки признаков

In [ ]:
df_processed = df.copy()

Нормализация представлений молекул

In [ ]:
PandasTools.AddMoleculeColumnToFrame(
    df_processed,
    'SMILES_Solute',
    'Mol_Solute')
PandasTools.AddMoleculeColumnToFrame(
    df_processed,
    'SMILES_Solvent',
    'Mol_Solvent')
df_processed.head()

,SMILES_Solute,Temperature_K,Solvent,SMILES_Solvent,Solubility(mole_fraction),Solubility(mol/L),LogS(mol/L),Compound_Name,CAS,PubChem_CID,FDA_Approved,Source,Mol_Solute,Mol_Solvent
0,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,311.25,ethanol,CCO,0.0006,0.010083,-1.996419,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670ad50>,<rdkit.Chem.rdchem.Mol object at 0x793f092fece0>
1,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,314.65,ethanol,CCO,0.0012,0.020100,-1.696799,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670a500>,<rdkit.Chem.rdchem.Mol object at 0x793ec7c53a70>
2,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,319.15,ethanol,CCO,0.0020,0.033356,-1.476824,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670b450>,<rdkit.Chem.rdchem.Mol object at 0x793f091df300>
3,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,322.15,ethanol,CCO,0.0050,0.083356,-1.079064,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670a6c0>,<rdkit.Chem.rdchem.Mol object at 0x793f091df5a0>
4,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,324.15,ethanol,CCO,0.0139,0.233286,-0.632111,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670b220>,<rdkit.Chem.rdchem.Mol object at 0x793f091ded50>

Получение моргановских отпечатков для каждой молекулы

In [ ]:
from rdkit.Chem import AllChem

def morgan_fp(mol):
  morgan = AllChem.GetMorganGenerator(radius=2, fpSize=512)
  return morgan.GetFingerprint(mol)

In [ ]:
df_processed['Morgan_Solute'] = df_processed['Mol_Solute'].apply(morgan_fp)
df_processed['Morgan_Solvent'] = df_processed['Mol_Solvent'].apply(morgan_fp)
df_processed.head()

,SMILES_Solute,Temperature_K,Solvent,SMILES_Solvent,Solubility(mole_fraction),Solubility(mol/L),LogS(mol/L),Compound_Name,CAS,PubChem_CID,FDA_Approved,Source,Mol_Solute,Mol_Solvent,Morgan_Solute,Morgan_Solvent
0,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,311.25,ethanol,CCO,0.0006,0.010083,-1.996419,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670ad50>,<rdkit.Chem.rdchem.Mol object at 0x793f092fece0>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,314.65,ethanol,CCO,0.0012,0.020100,-1.696799,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670a500>,<rdkit.Chem.rdchem.Mol object at 0x793ec7c53a70>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,319.15,ethanol,CCO,0.0020,0.033356,-1.476824,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670b450>,<rdkit.Chem.rdchem.Mol object at 0x793f091df300>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,322.15,ethanol,CCO,0.0050,0.083356,-1.079064,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670a6c0>,<rdkit.Chem.rdchem.Mol object at 0x793f091df5a0>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,CCCCCCCCCCCCCCCCCCCC(=O)OCCO,324.15,ethanol,CCO,0.0139,0.233286,-0.632111,Ethylene glycol monoeicosate,26158-80-5,538813.0,No,10.1007/bf00649573,<rdkit.Chem.rdchem.Mol object at 0x793ec670b220>,<rdkit.Chem.rdchem.Mol object at 0x793f091ded50>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [ ]:
df_processed.columns

Index(['SMILES_Solute', 'Temperature_K', 'Solvent', 'SMILES_Solvent',
       'Solubility(mole_fraction)', 'Solubility(mol/L)', 'LogS(mol/L)',
       'Compound_Name', 'CAS', 'PubChem_CID', 'FDA_Approved', 'Source',
       'Mol_Solute', 'Mol_Solvent', 'Morgan_Solute', 'Morgan_Solvent'],
      dtype='object')

Разделение выборки на обучающую и целевую функцию

In [ ]:
X = df_processed[['Temperature_K',
                  'Morgan_Solute',
                  'Morgan_Solvent']]
y = df_processed['LogS(mol/L)']

In [ ]:
X.head()

,Temperature_K,Morgan_Solute,Morgan_Solvent
0,311.25,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,314.65,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,319.15,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,322.15,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,324.15,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [ ]:
y.head()

0   -1.996419
1   -1.696799
2   -1.476824
3   -1.079064
4   -0.632111
Name: LogS(mol/L), dtype: float64

Кодирование категориального признака методом OneHotEncoder - названия растворителя

In [ ]:
X['Morgan_Solute'] = X['Morgan_Solute'].tolist()
X['Morgan_Solvent'] = X['Morgan_Solvent'].tolist()

/tmp/ipython-input-1126101153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Morgan_Solute'] = X['Morgan_Solute'].tolist()
/tmp/ipython-input-1126101153.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Morgan_Solvent'] = X['Morgan_Solvent'].tolist()

Приведение моргановских отпечатков типа bitvect к массиву numpy

In [ ]:
def bitvect_to_array(bitvect):
  arr = np.zeros((1,), dtype=int)
  DataStructs.ConvertToNumpyArray(bitvect, arr)
  return arr

In [ ]:
X['Morgan_Solute'] = X['Morgan_Solute'].apply(bitvect_to_array)
X['Morgan_Solvent'] = X['Morgan_Solvent'].apply(bitvect_to_array)

/tmp/ipython-input-1609987353.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Morgan_Solute'] = X['Morgan_Solute'].apply(bitvect_to_array)
/tmp/ipython-input-1609987353.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Morgan_Solvent'] = X['Morgan_Solvent'].apply(bitvect_to_array)

Вертикальное соединения массивов (по строкам)

In [ ]:
solute_fp = np.vstack(X['Morgan_Solute'].values)
solvent_fp = np.vstack(X['Morgan_Solvent'].values)

Объединение данных для получения результирующей выборки

In [ ]:
X_base = X.drop(['Morgan_Solute', 'Morgan_Solvent'], axis=1)

solute_df = pd.DataFrame(solute_fp, index=X.index).add_prefix('SoluteFP_')
solvent_df = pd.DataFrame(solvent_fp, index=X.index).add_prefix('SolventFP_')

X_final = pd.concat([X_base, solute_df, solvent_df], axis=1)

In [ ]:
X_final.shape, y.shape

((93929, 1025), (93929,))

Разделение на трейн и тест для обучения модели

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y,
    test_size=0.2,
    random_state=42
)

Подбор оптимальных гиперпараметров для модели бустинга

In [ ]:
def objective(trial):
  n_estimators = trial.suggest_int('n_estimators', 100, 1000)
  max_depth = trial.suggest_int('max_depth', 3, 10)
  learning_rate = trial.suggest_float('learning_rate', 0.01, 0.1)
  subsample = trial.suggest_float('subsample', 0.5, 1.0)
  min_child_weight = trial.suggest_int('min_child_weight', 1, 10)
  gamma = trial.suggest_float('gamma', 0, 5)

  model = xgb.XGBRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        learning_rate=learning_rate,
        subsample=subsample,
        min_child_weight=min_child_weight,
        gamma=gamma,
        random_state=42,
        tree_method='hist',
        device='cuda'
    )
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  rmse = mean_squared_error(y_test, y_pred)
  r2 = r2_score(y_test, y_pred)

  print(f"Trial {trial.number}: RMSE={rmse:.4f}, R2={r2:.4f}")

  return rmse

Обучение модели

In [ ]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print(f"Best trial value (RMSE): {study.best_value}")
print(f"Best hyperparameters: {study.best_params}")

[I 2025-10-05 14:44:55,778] A new study created in memory with name: no-name-932f90c0-076e-4de8-9ece-6a597d591f76
/usr/local/lib/python3.12/dist-packages/xgboost/core.py:729: UserWarning: [14:45:09] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)
[I 2025-10-05 14:45:09,975] Trial 0 finished with value: 0.5147531461499818 and parameters: {'n_estimators': 294, 'max_depth': 8, 'learning_rate': 0.0140160665731306, 'subsample': 0.7010858480832709, 'min_child_weight': 9, 'gamma': 0.2076101414382553}. Best is trial 0 with value: 0.5147531461499818.

Trial 0: RMSE=0.5148, R2=0.6509

[I 2025-10-05 14:45:24,046] Trial 1 finished with value: 0.12436957423166098 and parameters: {'n_estimators': 265, 'max_depth': 10, 'learning_rate': 0.06855403158115012, 'subsample': 0.8657061759388995, 'min_child_weight': 5, 'gamma': 1.1984023111128606}. Best is trial 1 with value: 0.12436957423166098.

Trial 1: RMSE=0.1244, R2=0.9157

[I 2025-10-05 14:45:40,082] Trial 2 finished with value: 0.24221568448214756 and parameters: {'n_estimators': 971, 'max_depth': 5, 'learning_rate': 0.08550209628152534, 'subsample': 0.6397827114480941, 'min_child_weight': 2, 'gamma': 3.1031924848040466}. Best is trial 1 with value: 0.12436957423166098.

Trial 2: RMSE=0.2422, R2=0.8357

[I 2025-10-05 14:45:56,784] Trial 3 finished with value: 0.13329286497721102 and parameters: {'n_estimators': 882, 'max_depth': 8, 'learning_rate': 0.09843843383056652, 'subsample': 0.5466861969735032, 'min_child_weight': 5, 'gamma': 1.2718938333009806}. Best is trial 1 with value: 0.12436957423166098.

Trial 3: RMSE=0.1333, R2=0.9096

[I 2025-10-05 14:46:14,284] Trial 4 finished with value: 0.5966991764019083 and parameters: {'n_estimators': 849, 'max_depth': 4, 'learning_rate': 0.017773493596002016, 'subsample': 0.8245052295626614, 'min_child_weight': 3, 'gamma': 3.1607521087614527}. Best is trial 1 with value: 0.12436957423166098.

Trial 4: RMSE=0.5967, R2=0.5953

[I 2025-10-05 14:46:26,788] Trial 5 finished with value: 0.6801871671697061 and parameters: {'n_estimators': 219, 'max_depth': 8, 'learning_rate': 0.01070662091194258, 'subsample': 0.630076991472978, 'min_child_weight': 8, 'gamma': 4.756515585938933}. Best is trial 1 with value: 0.12436957423166098.

Trial 5: RMSE=0.6802, R2=0.5387

[I 2025-10-05 14:46:42,383] Trial 6 finished with value: 0.19685275556050724 and parameters: {'n_estimators': 763, 'max_depth': 9, 'learning_rate': 0.08006114641357673, 'subsample': 0.7122327683758616, 'min_child_weight': 3, 'gamma': 3.6963562326975756}. Best is trial 1 with value: 0.12436957423166098.

Trial 6: RMSE=0.1969, R2=0.8665

[I 2025-10-05 14:46:53,725] Trial 7 finished with value: 0.9486103525391809 and parameters: {'n_estimators': 316, 'max_depth': 4, 'learning_rate': 0.010897902080795833, 'subsample': 0.5707758183970313, 'min_child_weight': 5, 'gamma': 0.5614608522640285}. Best is trial 1 with value: 0.12436957423166098.

Trial 7: RMSE=0.9486, R2=0.3567

[I 2025-10-05 14:47:03,546] Trial 8 finished with value: 0.7078718029054445 and parameters: {'n_estimators': 255, 'max_depth': 3, 'learning_rate': 0.07165208089586271, 'subsample': 0.8876744278240452, 'min_child_weight': 7, 'gamma': 2.3650731146619948}. Best is trial 1 with value: 0.12436957423166098.

Trial 8: RMSE=0.7079, R2=0.5199

[I 2025-10-05 14:47:13,266] Trial 9 finished with value: 0.6277657751370986 and parameters: {'n_estimators': 111, 'max_depth': 5, 'learning_rate': 0.0699471188555329, 'subsample': 0.7067720793248098, 'min_child_weight': 4, 'gamma': 0.536487472739221}. Best is trial 1 with value: 0.12436957423166098.

Trial 9: RMSE=0.6278, R2=0.5743

[I 2025-10-05 14:47:30,990] Trial 10 finished with value: 0.13756793327145914 and parameters: {'n_estimators': 538, 'max_depth': 10, 'learning_rate': 0.04391901360917578, 'subsample': 0.9911223530086388, 'min_child_weight': 1, 'gamma': 1.6089050249152357}. Best is trial 1 with value: 0.12436957423166098.

Trial 10: RMSE=0.1376, R2=0.9067

[I 2025-10-05 14:47:46,260] Trial 11 finished with value: 0.13985295279369722 and parameters: {'n_estimators': 548, 'max_depth': 10, 'learning_rate': 0.09474021698496041, 'subsample': 0.5137287945737201, 'min_child_weight': 6, 'gamma': 1.5805791630194115}. Best is trial 1 with value: 0.12436957423166098.

Trial 11: RMSE=0.1399, R2=0.9052

[I 2025-10-05 14:48:03,356] Trial 12 finished with value: 0.16274643746801903 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.05398860340420011, 'subsample': 0.8270304885932649, 'min_child_weight': 5, 'gamma': 1.5017437375884737}. Best is trial 1 with value: 0.12436957423166098.

Trial 12: RMSE=0.1627, R2=0.8896

[I 2025-10-05 14:48:16,794] Trial 13 finished with value: 0.13816841323002524 and parameters: {'n_estimators': 430, 'max_depth': 9, 'learning_rate': 0.09950002214893398, 'subsample': 0.9132335970443464, 'min_child_weight': 10, 'gamma': 1.141351216559314}. Best is trial 1 with value: 0.12436957423166098.

Trial 13: RMSE=0.1382, R2=0.9063

[I 2025-10-05 14:48:36,221] Trial 14 finished with value: 0.184593610194492 and parameters: {'n_estimators': 970, 'max_depth': 7, 'learning_rate': 0.037058501293313034, 'subsample': 0.7943166523158125, 'min_child_weight': 6, 'gamma': 2.067552676098696}. Best is trial 1 with value: 0.12436957423166098.

Trial 14: RMSE=0.1846, R2=0.8748

[I 2025-10-05 14:48:54,215] Trial 15 finished with value: 0.12708581106458958 and parameters: {'n_estimators': 649, 'max_depth': 9, 'learning_rate': 0.06321491259121097, 'subsample': 0.9976666326773526, 'min_child_weight': 4, 'gamma': 0.8594711247614168}. Best is trial 1 with value: 0.12436957423166098.

Trial 15: RMSE=0.1271, R2=0.9138

[I 2025-10-05 14:49:11,815] Trial 16 finished with value: 0.11401910065186407 and parameters: {'n_estimators': 658, 'max_depth': 10, 'learning_rate': 0.06095248602589909, 'subsample': 0.9979705900033988, 'min_child_weight': 3, 'gamma': 0.8359301135212638}. Best is trial 16 with value: 0.11401910065186407.

Trial 16: RMSE=0.1140, R2=0.9227

[I 2025-10-05 14:49:32,716] Trial 17 finished with value: 0.07714834094773969 and parameters: {'n_estimators': 458, 'max_depth': 10, 'learning_rate': 0.051384317654646905, 'subsample': 0.9213267365948028, 'min_child_weight': 1, 'gamma': 0.19553540229604083}. Best is trial 17 with value: 0.07714834094773969.

Trial 17: RMSE=0.0771, R2=0.9477

[I 2025-10-05 14:49:45,944] Trial 18 finished with value: 0.3979862334573405 and parameters: {'n_estimators': 396, 'max_depth': 6, 'learning_rate': 0.03289236495810415, 'subsample': 0.9329594683157412, 'min_child_weight': 1, 'gamma': 0.10544622385879562}. Best is trial 17 with value: 0.07714834094773969.

Trial 18: RMSE=0.3980, R2=0.7301

[I 2025-10-05 14:50:07,252] Trial 19 finished with value: 0.07272037597562865 and parameters: {'n_estimators': 461, 'max_depth': 10, 'learning_rate': 0.05353460973995613, 'subsample': 0.9511490911448504, 'min_child_weight': 2, 'gamma': 0.08259103510032961}. Best is trial 19 with value: 0.07272037597562865.

Trial 19: RMSE=0.0727, R2=0.9507

[I 2025-10-05 14:50:26,435] Trial 20 finished with value: 0.10408918576179937 and parameters: {'n_estimators': 455, 'max_depth': 9, 'learning_rate': 0.049828921405153485, 'subsample': 0.9277568345707887, 'min_child_weight': 2, 'gamma': 0.07390498450437274}. Best is trial 19 with value: 0.07272037597562865.

Trial 20: RMSE=0.1041, R2=0.9294

[I 2025-10-05 14:50:45,567] Trial 21 finished with value: 0.11207086725792546 and parameters: {'n_estimators': 439, 'max_depth': 9, 'learning_rate': 0.048974965900645026, 'subsample': 0.9429376585921219, 'min_child_weight': 2, 'gamma': 0.024727415466232444}. Best is trial 19 with value: 0.07272037597562865.

Trial 21: RMSE=0.1121, R2=0.9240

[I 2025-10-05 14:51:07,552] Trial 22 finished with value: 0.132775501705032 and parameters: {'n_estimators': 485, 'max_depth': 10, 'learning_rate': 0.027778319178729513, 'subsample': 0.9484605337315404, 'min_child_weight': 1, 'gamma': 0.512201750999954}. Best is trial 19 with value: 0.07272037597562865.

Trial 22: RMSE=0.1328, R2=0.9100

[I 2025-10-05 14:51:24,046] Trial 23 finished with value: 0.138442270439804 and parameters: {'n_estimators': 381, 'max_depth': 9, 'learning_rate': 0.04397067315718144, 'subsample': 0.8647689024193196, 'min_child_weight': 2, 'gamma': 0.41659041360886623}. Best is trial 19 with value: 0.07272037597562865.

Trial 23: RMSE=0.1384, R2=0.9061

[I 2025-10-05 14:51:42,879] Trial 24 finished with value: 0.09431643287389604 and parameters: {'n_estimators': 589, 'max_depth': 8, 'learning_rate': 0.056473302388650774, 'subsample': 0.796755295982357, 'min_child_weight': 2, 'gamma': 0.014457213967576266}. Best is trial 19 with value: 0.07272037597562865.

Trial 24: RMSE=0.0943, R2=0.9360

[I 2025-10-05 14:51:59,547] Trial 25 finished with value: 0.16315528521174602 and parameters: {'n_estimators': 606, 'max_depth': 8, 'learning_rate': 0.05919020036343084, 'subsample': 0.7574474553918514, 'min_child_weight': 1, 'gamma': 1.9584725451738074}. Best is trial 19 with value: 0.07272037597562865.

Trial 25: RMSE=0.1632, R2=0.8894

[I 2025-10-05 14:52:15,253] Trial 26 finished with value: 0.2146505957342692 and parameters: {'n_estimators': 507, 'max_depth': 7, 'learning_rate': 0.04096107101287421, 'subsample': 0.7701312775186675, 'min_child_weight': 3, 'gamma': 0.8531333613028059}. Best is trial 19 with value: 0.07272037597562865.

Trial 26: RMSE=0.2147, R2=0.8544

[I 2025-10-05 14:52:29,525] Trial 27 finished with value: 0.2681806484837626 and parameters: {'n_estimators': 598, 'max_depth': 6, 'learning_rate': 0.054279743932413166, 'subsample': 0.8471387319941562, 'min_child_weight': 4, 'gamma': 4.442818968719532}. Best is trial 19 with value: 0.07272037597562865.

Trial 27: RMSE=0.2682, R2=0.8181

[I 2025-10-05 14:52:48,088] Trial 28 finished with value: 0.19497690266418746 and parameters: {'n_estimators': 364, 'max_depth': 10, 'learning_rate': 0.024289609731010617, 'subsample': 0.8037026936310561, 'min_child_weight': 2, 'gamma': 0.8486472111378109}. Best is trial 19 with value: 0.07272037597562865.

Trial 28: RMSE=0.1950, R2=0.8678

[I 2025-10-05 14:53:07,016] Trial 29 finished with value: 0.08540332304816967 and parameters: {'n_estimators': 712, 'max_depth': 8, 'learning_rate': 0.07878211671270553, 'subsample': 0.9045721130824127, 'min_child_weight': 1, 'gamma': 0.32646144530137966}. Best is trial 19 with value: 0.07272037597562865.

Trial 29: RMSE=0.0854, R2=0.9421
Best trial value (RMSE): 0.07272037597562865
Best hyperparameters: {'n_estimators': 461, 'max_depth': 10, 'learning_rate': 0.05353460973995613, 'subsample': 0.9511490911448504, 'min_child_weight': 2, 'gamma': 0.08259103510032961}

In [ ]:
xgb_model = xgb.XGBRegressor(
        n_estimators=study.best_params['n_estimators'],
        max_depth=study.best_params['max_depth'],
        learning_rate=study.best_params['learning_rate'],
        subsample=study.best_params['subsample'],
        min_child_weight=study.best_params['min_child_weight'],
        gamma=study.best_params['gamma'],
        random_state=42,
        tree_method='hist',
        device='cuda'
    )
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.08259103510032961, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05353460973995613, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=2, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=461, n_jobs=None,
             num_parallel_tree=None, ...)

In [ ]:
from joblib import dump, load
from pathlib import Path

model_dir_path = '/content/drive/MyDrive/XGB_solubility'

dump(xgb_model, Path(model_dir_path) / 'model.joblib')

['/content/drive/MyDrive/XGB_solubility/xgb_for_solubility_pred.joblib']